// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: goldpe_arduino_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

lv_obj_t* active_textarea = NULL;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Container1;
void ui_event_Buttonnext1(lv_event_t * e);
lv_obj_t * ui_Buttonnext1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Image1;
// CUSTOM VARIABLES


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Container2;
void ui_event_TextAreaaadhaar2(lv_event_t * e);
lv_obj_t * ui_TextAreaaadhaar2;
void ui_event_TextAreamobile2(lv_event_t * e);
lv_obj_t * ui_TextAreamobile2;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
void ui_event_Buttonprev2(lv_event_t * e);
lv_obj_t * ui_Buttonprev2;
lv_obj_t * ui_Label6;
void ui_event_Buttonnext2(lv_event_t * e);
lv_obj_t * ui_Buttonnext2;
lv_obj_t * ui_Label7;
// CUSTOM VARIABLES


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Container3;
void ui_event_Buttonnext3(lv_event_t * e);
lv_obj_t * ui_Buttonnext3;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Labelaadhaar2;
void ui_event_Buttonprev3(lv_event_t * e);
lv_obj_t * ui_Buttonprev3;
lv_obj_t * ui_Label9;
void ui_event_TextAreaenterotp(lv_event_t * e);
lv_obj_t * ui_TextAreaenterotp;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
// CUSTOM VARIABLES


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_TextArea;
lv_obj_t * ui_Container4;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label12;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label13;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label14;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label15;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label16;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label17;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label18;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label19;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label20;
void ui_event_Buttoncancel(lv_event_t * e);
lv_obj_t * ui_Buttoncancel;
lv_obj_t * ui_Label21;
void ui_event_Buttonclear(lv_event_t * e);
lv_obj_t * ui_Buttonclear;
lv_obj_t * ui_Label22;
void ui_event_Buttonback(lv_event_t * e);
lv_obj_t * ui_Buttonback;
lv_obj_t * ui_Label23;
void ui_event_hashButton(lv_event_t * e);
lv_obj_t * ui_hashButton;
lv_obj_t * ui_Label24;
void ui_event_Button0(lv_event_t * e);
lv_obj_t * ui_Button0;
lv_obj_t * ui_Label25;
void ui_event_starButton(lv_event_t * e);
lv_obj_t * ui_starButton;
lv_obj_t * ui_Label26;
void ui_event_Buttonenter(lv_event_t * e);
lv_obj_t * ui_Buttonenter;
lv_obj_t * ui_Label27;
// CUSTOM VARIABLES


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t * ui_Screen5;
lv_obj_t * ui_Container5;
void ui_event_TextAreaamount2(lv_event_t * e);
lv_obj_t * ui_TextAreaamount2;
void ui_event_Buttonprev4(lv_event_t * e);
lv_obj_t * ui_Buttonprev4;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Label29;
// CUSTOM VARIABLES


// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
lv_obj_t * ui_Screen6;
lv_obj_t * ui_TextAreaotp;
lv_obj_t * ui_Container6;
void ui_event_Button2otp(lv_event_t * e);
lv_obj_t * ui_Button2otp;
lv_obj_t * ui_Label30;
void ui_event_Button9otp(lv_event_t * e);
lv_obj_t * ui_Button9otp;
lv_obj_t * ui_Label31;
void ui_event_Button8otp(lv_event_t * e);
lv_obj_t * ui_Button8otp;
lv_obj_t * ui_Label32;
void ui_event_Button7otp(lv_event_t * e);
lv_obj_t * ui_Button7otp;
lv_obj_t * ui_Label33;
void ui_event_Button6otp(lv_event_t * e);
lv_obj_t * ui_Button6otp;
lv_obj_t * ui_Label34;
void ui_event_Button5otp(lv_event_t * e);
lv_obj_t * ui_Button5otp;
lv_obj_t * ui_Label35;
void ui_event_Button4otp(lv_event_t * e);
lv_obj_t * ui_Button4otp;
lv_obj_t * ui_Label36;
void ui_event_Button3otp(lv_event_t * e);
lv_obj_t * ui_Button3otp;
lv_obj_t * ui_Label37;
void ui_event_Button1otp(lv_event_t * e);
lv_obj_t * ui_Button1otp;
lv_obj_t * ui_Label38;
void ui_event_Buttoncancelotp(lv_event_t * e);
lv_obj_t * ui_Buttoncancelotp;
lv_obj_t * ui_Label39;
void ui_event_Buttonclearotp(lv_event_t * e);
lv_obj_t * ui_Buttonclearotp;
lv_obj_t * ui_Label40;
void ui_event_Buttonbackotp(lv_event_t * e);
lv_obj_t * ui_Buttonbackotp;
lv_obj_t * ui_Label41;
void ui_event_hashButtonotp(lv_event_t * e);
lv_obj_t * ui_hashButtonotp;
lv_obj_t * ui_Label42;
void ui_event_Button0otp(lv_event_t * e);
lv_obj_t * ui_Button0otp;
lv_obj_t * ui_Label43;
void ui_event_starButtonotp(lv_event_t * e);
lv_obj_t * ui_starButtonotp;
lv_obj_t * ui_Label44;
void ui_event_Buttonenterotp(lv_event_t * e);
lv_obj_t * ui_Buttonenterotp;
lv_obj_t * ui_Label45;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

bool sc1 = false;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Buttonnext1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        sc1 = true;
        //_ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_TextAreaaadhaar2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        active_textarea = lv_event_get_target(e);
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_TextAreamobile2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        active_textarea = lv_event_get_target(e);
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_Buttonprev2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Buttonnext2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Buttonnext3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_Buttonprev3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_TextAreaenterotp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        active_textarea = lv_event_get_target(e);
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_Screen6_screen_init);
        init_buttons_and_labels();
        shuffle_buttons();
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_two(e);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_nine(e);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_eight(e);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_seven(e);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_six(e);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_five(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_four(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_three(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_one(e);
    }
}

void ui_event_Buttoncancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_cancel(e);
    }
}

void ui_event_Buttonclear(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_clear(e);
    }
}

void ui_event_Buttonback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_back(e);
    }
}

void ui_event_hashButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_hash(e);
    }
}

void ui_event_Button0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_zero(e);
    }
}

void ui_event_starButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_star(e);
    }
}

void ui_event_Buttonenter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_enter(e);
    }
}

void ui_event_TextAreaamount2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        active_textarea = lv_event_get_target(e);
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_Buttonprev4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_Button2otp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_two_otp(e);
    }
}

void ui_event_Button9otp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_nine_otp(e);
    }
}

void ui_event_Button8otp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_eight_otp(e);
    }
}

void ui_event_Button7otp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_seven_otp(e);
    }
}

void ui_event_Button6otp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_six_otp(e);
    }
}

void ui_event_Button5otp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_five_otp(e);
    }
}

void ui_event_Button4otp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_four_otp(e);
    }
}

void ui_event_Button3otp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_three_otp(e);
    }
}

void ui_event_Button1otp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_one_otp(e);
    }
}

void ui_event_Buttoncancelotp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_cancel_otp(e);
    }
}

void ui_event_Buttonclearotp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_clear_otp(e);
    }
}

void ui_event_Buttonbackotp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_back_otp(e);
    }
}

void ui_event_hashButtonotp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_hash_otp(e);
    }
}

void ui_event_Button0otp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_zero_otp(e);
    }
}

void ui_event_starButtonotp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_star_otp(e);
    }
}

void ui_event_Buttonenterotp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        press_enter_otp(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui_Screen6_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
