// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: goldpe_arduino_Project

#ifndef _GOLDPE_ARDUINO_PROJECT_UI_H
#define _GOLDPE_ARDUINO_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
void ui_event_Buttonnext1(lv_event_t * e);
extern lv_obj_t * ui_Buttonnext1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container2;
void ui_event_TextAreaaadhaar2(lv_event_t * e);
extern lv_obj_t * ui_TextAreaaadhaar2;
void ui_event_TextAreamobile2(lv_event_t * e);
extern lv_obj_t * ui_TextAreamobile2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
void ui_event_Buttonprev2(lv_event_t * e);
extern lv_obj_t * ui_Buttonprev2;
extern lv_obj_t * ui_Label6;
void ui_event_Buttonnext2(lv_event_t * e);
extern lv_obj_t * ui_Buttonnext2;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Container3;
void ui_event_Buttonnext3(lv_event_t * e);
extern lv_obj_t * ui_Buttonnext3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Labelaadhaar2;
void ui_event_Buttonprev3(lv_event_t * e);
extern lv_obj_t * ui_Buttonprev3;
extern lv_obj_t * ui_Label9;
void ui_event_TextAreaenterotp(lv_event_t * e);
extern lv_obj_t * ui_TextAreaenterotp;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_TextArea;
extern lv_obj_t * ui_Container4;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label12;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label13;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label14;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label15;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label16;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label17;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label18;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label19;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label20;
void ui_event_Buttoncancel(lv_event_t * e);
extern lv_obj_t * ui_Buttoncancel;
extern lv_obj_t * ui_Label21;
void ui_event_Buttonclear(lv_event_t * e);
extern lv_obj_t * ui_Buttonclear;
extern lv_obj_t * ui_Label22;
void ui_event_Buttonback(lv_event_t * e);
extern lv_obj_t * ui_Buttonback;
extern lv_obj_t * ui_Label23;
void ui_event_hashButton(lv_event_t * e);
extern lv_obj_t * ui_hashButton;
extern lv_obj_t * ui_Label24;
void ui_event_Button0(lv_event_t * e);
extern lv_obj_t * ui_Button0;
extern lv_obj_t * ui_Label25;
void ui_event_starButton(lv_event_t * e);
extern lv_obj_t * ui_starButton;
extern lv_obj_t * ui_Label26;
void ui_event_Buttonenter(lv_event_t * e);
extern lv_obj_t * ui_Buttonenter;
extern lv_obj_t * ui_Label27;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Container5;
void ui_event_TextAreaamount2(lv_event_t * e);
extern lv_obj_t * ui_TextAreaamount2;
void ui_event_Buttonprev4(lv_event_t * e);
extern lv_obj_t * ui_Buttonprev4;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
// CUSTOM VARIABLES

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_TextAreaotp;
extern lv_obj_t * ui_Container6;
void ui_event_Button2otp(lv_event_t * e);
extern lv_obj_t * ui_Button2otp;
extern lv_obj_t * ui_Label30;
void ui_event_Button9otp(lv_event_t * e);
extern lv_obj_t * ui_Button9otp;
extern lv_obj_t * ui_Label31;
void ui_event_Button8otp(lv_event_t * e);
extern lv_obj_t * ui_Button8otp;
extern lv_obj_t * ui_Label32;
void ui_event_Button7otp(lv_event_t * e);
extern lv_obj_t * ui_Button7otp;
extern lv_obj_t * ui_Label33;
void ui_event_Button6otp(lv_event_t * e);
extern lv_obj_t * ui_Button6otp;
extern lv_obj_t * ui_Label34;
void ui_event_Button5otp(lv_event_t * e);
extern lv_obj_t * ui_Button5otp;
extern lv_obj_t * ui_Label35;
void ui_event_Button4otp(lv_event_t * e);
extern lv_obj_t * ui_Button4otp;
extern lv_obj_t * ui_Label36;
void ui_event_Button3otp(lv_event_t * e);
extern lv_obj_t * ui_Button3otp;
extern lv_obj_t * ui_Label37;
void ui_event_Button1otp(lv_event_t * e);
extern lv_obj_t * ui_Button1otp;
extern lv_obj_t * ui_Label38;
void ui_event_Buttoncancelotp(lv_event_t * e);
extern lv_obj_t * ui_Buttoncancelotp;
extern lv_obj_t * ui_Label39;
void ui_event_Buttonclearotp(lv_event_t * e);
extern lv_obj_t * ui_Buttonclearotp;
extern lv_obj_t * ui_Label40;
void ui_event_Buttonbackotp(lv_event_t * e);
extern lv_obj_t * ui_Buttonbackotp;
extern lv_obj_t * ui_Label41;
void ui_event_hashButtonotp(lv_event_t * e);
extern lv_obj_t * ui_hashButtonotp;
extern lv_obj_t * ui_Label42;
void ui_event_Button0otp(lv_event_t * e);
extern lv_obj_t * ui_Button0otp;
extern lv_obj_t * ui_Label43;
void ui_event_starButtonotp(lv_event_t * e);
extern lv_obj_t * ui_starButtonotp;
extern lv_obj_t * ui_Label44;
void ui_event_Buttonenterotp(lv_event_t * e);
extern lv_obj_t * ui_Buttonenterotp;
extern lv_obj_t * ui_Label45;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

extern bool sc1;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1233302218);    // assets/Screenshot 2025-01-27 201256-photoaidcom-cropped.png

// FONTS
LV_FONT_DECLARE(ui_font_Fontb);
LV_FONT_DECLARE(ui_font_Fontbsm);
LV_FONT_DECLARE(ui_font_Fontcan);
LV_FONT_DECLARE(ui_font_Fontnew);
LV_FONT_DECLARE(ui_font_Fontnum);
LV_FONT_DECLARE(ui_font_Fontsim);
LV_FONT_DECLARE(ui_font_Fontsimsmall);
LV_FONT_DECLARE(ui_font_Fontsmall);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
