// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: goldpe_arduino_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void init_buttons_and_labels();
void shuffle_buttons(void);

extern bool adhr;

void press_two(lv_event_t * e);
void press_nine(lv_event_t * e);
void press_eight(lv_event_t * e);
void press_seven(lv_event_t * e);
void press_six(lv_event_t * e);
void press_five(lv_event_t * e);
void press_four(lv_event_t * e);
void press_three(lv_event_t * e);
void press_one(lv_event_t * e);
void press_cancel(lv_event_t * e);
void press_clear(lv_event_t * e);
void press_back(lv_event_t * e);
void press_hash(lv_event_t * e);
void press_zero(lv_event_t * e);
void press_star(lv_event_t * e);
void press_enter(lv_event_t * e);
void press_two_otp(lv_event_t * e);
void press_nine_otp(lv_event_t * e);
void press_eight_otp(lv_event_t * e);
void press_seven_otp(lv_event_t * e);
void press_six_otp(lv_event_t * e);
void press_five_otp(lv_event_t * e);
void press_four_otp(lv_event_t * e);
void press_three_otp(lv_event_t * e);
void press_one_otp(lv_event_t * e);
void press_cancel_otp(lv_event_t * e);
void press_clear_otp(lv_event_t * e);
void press_back_otp(lv_event_t * e);
void press_hash_otp(lv_event_t * e);
void press_zero_otp(lv_event_t * e);
void press_star_otp(lv_event_t * e);
void press_enter_otp(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
