// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: goldpe_arduino_Project

#include "ui.h"
#include <stdlib.h>
#include <stdio.h>
#include <time.h>

lv_obj_t *buttons[10];

extern lv_obj_t* previous_screen;
extern lv_obj_t* active_textarea;

const char * aadhaar_input;

bool change_screen = false;

bool adhr = false;


void init_buttons_and_labels() 
{
    buttons[0] = ui_Button0otp;
    buttons[1] = ui_Button1otp;
    buttons[2] = ui_Button2otp;
    buttons[3] = ui_Button3otp;
    buttons[4] = ui_Button4otp;
    buttons[5] = ui_Button5otp;
    buttons[6] = ui_Button6otp;
    buttons[7] = ui_Button7otp;
    buttons[8] = ui_Button8otp;
    buttons[9] = ui_Button9otp;
}

void shuffle_buttons(void) 
{
    lv_coord_t x_positions[10] = {-88, -221, -88, 51, -221, -88, 51, -221, -88, 51}; 
    lv_coord_t y_positions[10] = {141, -138, -138, -138, -45, -45, -45, 48, 48, 48};

    lv_coord_t shuffled_x[10]; 
    lv_coord_t shuffled_y[10]; 

    // Copy original positions to shuffled arrays
    for (int i = 0; i < 10; i++) 
    {
        shuffled_x[i] = x_positions[i];
        shuffled_y[i] = y_positions[i];
    }

    // Seed the random number generator
    srand(time(NULL));

    // Shuffle the x and y positions
    for (int i = 0; i < 10; i++) 
    {
        int rand_index = rand() % 10;  // Random index
        
        // Swap the X positions
        lv_coord_t temp_x = shuffled_x[i];
        shuffled_x[i] = shuffled_x[rand_index];
        shuffled_x[rand_index] = temp_x;
        
        // Swap the Y positions
        lv_coord_t temp_y = shuffled_y[i];
        shuffled_y[i] = shuffled_y[rand_index];
        shuffled_y[rand_index] = temp_y;
    }

    // Reposition the buttons to the shuffled positions
    for (int i = 0; i < 10; i++) 
    {
        lv_obj_set_pos(buttons[i], shuffled_x[i], shuffled_y[i]);
    }
}

void press_number(lv_event_t * e, const char * number)
{
    if(active_textarea == ui_TextAreamobile2)
    {
        lv_textarea_set_max_length(ui_TextArea, 10);
    }
    else if(active_textarea == ui_TextAreaaadhaar2)
    {
        lv_textarea_set_max_length(ui_TextArea, 12);
    }
    
    lv_textarea_add_text(ui_TextArea, number);
}


void press_two(lv_event_t * e)
{
	press_number(e, "2");
}

void press_nine(lv_event_t * e)
{
	press_number(e, "9");
}

void press_eight(lv_event_t * e)
{
	press_number(e, "8");
}

void press_seven(lv_event_t * e)
{
	press_number(e, "7");
}

void press_six(lv_event_t * e)
{
	press_number(e, "6");
}

void press_five(lv_event_t * e)
{
	press_number(e, "5");
}

void press_four(lv_event_t * e)
{
	press_number(e, "4");
}

void press_three(lv_event_t * e)
{
	press_number(e, "3");
}

void press_one(lv_event_t * e)
{
	press_number(e, "1");
}

void press_cancel(lv_event_t * e)
{
	lv_textarea_set_text(ui_TextArea, "");
}

void press_clear(lv_event_t * e)
{
	lv_textarea_set_text(ui_TextArea, "");
}

void press_back(lv_event_t * e)
{
	lv_textarea_del_char(ui_TextArea);
}

void press_hash(lv_event_t * e)
{
	press_number(e, "#");
}

void press_zero(lv_event_t * e)
{
	press_number(e, "0");
}

void press_star(lv_event_t * e)
{
	press_number(e, "*");
}

void press_enter(lv_event_t * e)
{
	const char * input = lv_textarea_get_text(ui_TextArea);
    size_t input_length = strlen(input);

	if (active_textarea == ui_TextAreamobile2) 
	{
        if (input_length == 10)
        {
        	
            printf("Mobile Number: %s\n", input);
            lv_textarea_set_text(active_textarea, input);
        }
        else{
            printf("Error: Mobile number must be exactly 10 digits.\n");
            return;
        }
    } 
	else if (active_textarea == ui_TextAreaaadhaar2) 
	{
        if (input_length == 12) 
        {
            aadhaar_input = input;
            lv_label_set_text(ui_Labelaadhaar2, aadhaar_input);
            printf("Aadhaar Number: %s\n", input);
            lv_textarea_set_text(active_textarea, input);
            lv_textarea_set_text(ui_TextArea, "");
            adhr = true;
        }
        else
        {
            printf("Error: Aadhaar number must be exactly 12 digits.\n");
            return;
        }
    }
	else if(active_textarea == ui_TextAreaamount2)
	{
		printf("Requested Amount : %s\n", input);
        lv_textarea_set_text(ui_TextAreamobile2, "");
        lv_textarea_set_text(ui_TextAreaaadhaar2, "");
        lv_label_set_text(ui_Labelaadhaar2, "");
        lv_textarea_set_text(ui_TextAreaenterotp, "");
        lv_textarea_set_text(ui_TextAreaamount2, "");

        lv_textarea_set_text(ui_TextArea, "");

        //lv_scr_load(ui_Screen1);
        return;
    }

    const char * mobile_input = lv_textarea_get_text(ui_TextAreamobile2);
    const char * aadhaar_input_check = lv_textarea_get_text(ui_TextAreaaadhaar2);

    if (strlen(mobile_input) == 10 && strlen(aadhaar_input_check) == 12)
    {

        //lv_scr_load(ui_Screen3);
        return;
    }


	lv_textarea_set_text(ui_TextArea, "");
}

void press_number_otp(lv_event_t * e, const char * number)
{
    lv_obj_set_style_text_font(ui_TextAreaotp, &lv_font_montserrat_28, LV_PART_MAIN);
    lv_textarea_add_text(ui_TextAreaotp, number);
}

void press_two_otp(lv_event_t * e)
{
	press_number_otp(e, "2");
}

void press_nine_otp(lv_event_t * e)
{
	press_number_otp(e, "9");
}

void press_eight_otp(lv_event_t * e)
{
	press_number_otp(e, "8");
}

void press_seven_otp(lv_event_t * e)
{
	press_number_otp(e, "7");
}

void press_six_otp(lv_event_t * e)
{
	press_number_otp(e, "6");
}

void press_five_otp(lv_event_t * e)
{
	press_number_otp(e, "5");
}

void press_four_otp(lv_event_t * e)
{
	press_number_otp(e, "4");
}

void press_three_otp(lv_event_t * e)
{
	press_number_otp(e, "3");
}

void press_one_otp(lv_event_t * e)
{
	press_number_otp(e, "1");
}

void press_cancel_otp(lv_event_t * e)
{
	lv_textarea_set_text(ui_TextAreaotp, "");
}

void press_clear_otp(lv_event_t * e)
{
	lv_textarea_set_text(ui_TextAreaotp, "");
}

void press_back_otp(lv_event_t * e)
{
	lv_textarea_del_char(ui_TextAreaotp);
}

void press_hash_otp(lv_event_t * e)
{
	press_number_otp(e, "#");
}

void press_zero_otp(lv_event_t * e)
{
	press_number_otp(e, "0");
}

void press_star_otp(lv_event_t * e)
{
	press_number_otp(e, "*");
}

void press_enter_otp(lv_event_t * e)
{
	const char * input = lv_textarea_get_text(ui_TextAreaotp);
    size_t input_length = strlen(input);
    if (input_length == 6) 
    {
        printf("OTP: %s\n", input);
        
        // if (active_textarea != NULL) 
        // {
        //     lv_textarea_set_text(active_textarea, input);
        // }
        // if (previous_screen != NULL) 
        // {
        //     lv_scr_load(previous_screen);
        //     previous_screen = NULL;   // Reset after returning
        //     active_textarea = NULL;   // Reset after use
        // }
        lv_textarea_set_text(ui_TextAreaotp, "");
        //lv_scr_load(ui_Screen5);
    }
    else
    {
        printf("Error: OTP must be exactly 6 digits.\n");
        return;
    }
}
