// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: goldpe_arduino_Project

#include "ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0xFFCA56), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen5, lv_color_hex(0xFF9A4E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen5, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 787);
    lv_obj_set_height(ui_Container5, 472);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextAreaamount2 = lv_textarea_create(ui_Container5);
    lv_obj_set_width(ui_TextAreaamount2, 397);
    lv_obj_set_height(ui_TextAreaamount2, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextAreaamount2, 184);
    lv_obj_set_y(ui_TextAreaamount2, -183);
    lv_obj_set_align(ui_TextAreaamount2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaamount2, "Enter your requested Amount");
    lv_textarea_set_one_line(ui_TextAreaamount2, true);
    lv_obj_set_style_text_font(ui_TextAreaamount2, &ui_font_Fontsimsmall, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextAreaamount2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextAreaamount2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextAreaamount2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_align(ui_TextAreaamount2, LV_TEXT_ALIGN_AUTO, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaamount2, &lv_font_montserrat_20, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Buttonprev4 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_Buttonprev4, 120);
    lv_obj_set_height(ui_Buttonprev4, 120);
    lv_obj_set_x(ui_Buttonprev4, -287);
    lv_obj_set_y(ui_Buttonprev4, 150);
    lv_obj_set_align(ui_Buttonprev4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonprev4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonprev4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Buttonprev4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Buttonprev4, lv_color_hex(0xFF9D4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonprev4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttonprev4, lv_color_hex(0xEE1410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttonprev4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Buttonprev4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Buttonprev4);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "<<");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xEE1410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label28, -5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &ui_font_Fontb, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -204);
    lv_obj_set_y(ui_Label29, -181);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "REQUESTED AMOUNT");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_Fontbsm, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextAreaamount2, ui_event_TextAreaamount2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonprev4, ui_event_Buttonprev4, LV_EVENT_ALL, NULL);

}
