// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: goldpe_arduino_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xFFCA56), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen2, lv_color_hex(0xFF9A4E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 790);
    lv_obj_set_height(ui_Container2, 474);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextAreaaadhaar2 = lv_textarea_create(ui_Container2);
    lv_obj_set_width(ui_TextAreaaadhaar2, 397);
    lv_obj_set_height(ui_TextAreaaadhaar2, 70);
    lv_obj_set_x(ui_TextAreaaadhaar2, 184);
    lv_obj_set_y(ui_TextAreaaadhaar2, -80);
    lv_obj_set_align(ui_TextAreaaadhaar2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaaadhaar2, "Enter 12 Digit Aadhaar Number");
    lv_obj_set_style_text_font(ui_TextAreaaadhaar2, &ui_font_Fontsimsmall, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextAreaaadhaar2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextAreaaadhaar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextAreaaadhaar2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_align(ui_TextAreaaadhaar2, LV_TEXT_ALIGN_AUTO, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaaadhaar2, &lv_font_montserrat_20,
                               LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_TextAreamobile2 = lv_textarea_create(ui_Container2);
    lv_obj_set_width(ui_TextAreamobile2, 397);
    lv_obj_set_height(ui_TextAreamobile2, 70);
    lv_obj_set_x(ui_TextAreamobile2, 184);
    lv_obj_set_y(ui_TextAreamobile2, -183);
    lv_obj_set_align(ui_TextAreamobile2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreamobile2, "Enter 10 Digit Mobile Number");
    lv_obj_set_style_text_font(ui_TextAreamobile2, &ui_font_Fontsimsmall, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextAreamobile2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextAreamobile2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextAreamobile2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_align(ui_TextAreamobile2, LV_TEXT_ALIGN_AUTO, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreamobile2, &lv_font_montserrat_20, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -204);
    lv_obj_set_y(ui_Label4, -80);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "AADHAAR NUMBER");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Fontbsm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -204);
    lv_obj_set_y(ui_Label5, -181);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "PHONE NUMBER");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Fontbsm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonprev2 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Buttonprev2, 120);
    lv_obj_set_height(ui_Buttonprev2, 120);
    lv_obj_set_x(ui_Buttonprev2, -287);
    lv_obj_set_y(ui_Buttonprev2, 150);
    lv_obj_set_align(ui_Buttonprev2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonprev2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonprev2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Buttonprev2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Buttonprev2, lv_color_hex(0xFF9D4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonprev2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttonprev2, lv_color_hex(0xEE1410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttonprev2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Buttonprev2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Buttonprev2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "<<");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xEE1410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label6, -5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Fontb, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonnext2 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Buttonnext2, 120);
    lv_obj_set_height(ui_Buttonnext2, 120);
    lv_obj_set_x(ui_Buttonnext2, 294);
    lv_obj_set_y(ui_Buttonnext2, 150);
    lv_obj_set_align(ui_Buttonnext2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonnext2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonnext2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Buttonnext2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Buttonnext2, lv_color_hex(0xFF9D4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonnext2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttonnext2, lv_color_hex(0xEE1410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttonnext2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Buttonnext2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Buttonnext2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, ">>");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xEE1410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label7, -5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Fontb, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextAreaaadhaar2, ui_event_TextAreaaadhaar2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreamobile2, ui_event_TextAreamobile2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonprev2, ui_event_Buttonprev2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonnext2, ui_event_Buttonnext2, LV_EVENT_ALL, NULL);

}
