// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: goldpe_arduino_Project

#include "ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0xFFCA56), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen6, lv_color_hex(0xFF9A4E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen6, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaotp = lv_textarea_create(ui_Screen6);
    lv_obj_set_width(ui_TextAreaotp, 536);
    lv_obj_set_height(ui_TextAreaotp, LV_SIZE_CONTENT);    /// 82
    lv_obj_set_x(ui_TextAreaotp, -9);
    lv_obj_set_y(ui_TextAreaotp, -184);
    lv_obj_set_align(ui_TextAreaotp, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_TextAreaotp, true);
    lv_obj_set_style_text_font(ui_TextAreaotp, &ui_font_Fontsim, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextAreaotp, lv_color_hex(0x908B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextAreaotp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextAreaotp, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_TextAreaotp, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaotp, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaotp, &lv_font_montserrat_28, LV_PART_SELECTED | LV_STATE_DEFAULT);


    ui_Container6 = lv_obj_create(ui_Screen6);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 620);
    lv_obj_set_height(ui_Container6, 383);
    lv_obj_set_x(ui_Container6, 1);
    lv_obj_set_y(ui_Container6, 45);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2otp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_Button2otp, 120);
    lv_obj_set_height(ui_Button2otp, 85);
    lv_obj_set_x(ui_Button2otp, -88);
    lv_obj_set_y(ui_Button2otp, -138);
    lv_obj_set_align(ui_Button2otp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2otp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2otp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2otp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button2otp, lv_color_hex(0x908B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button2otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button2otp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Button2otp);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "2");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label30, &ui_font_Fontsim, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9otp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_Button9otp, 120);
    lv_obj_set_height(ui_Button9otp, 85);
    lv_obj_set_x(ui_Button9otp, 51);
    lv_obj_set_y(ui_Button9otp, 48);
    lv_obj_set_align(ui_Button9otp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9otp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9otp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button9otp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button9otp, lv_color_hex(0x908B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button9otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button9otp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Button9otp);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "9");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label31, &ui_font_Fontsim, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8otp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_Button8otp, 120);
    lv_obj_set_height(ui_Button8otp, 85);
    lv_obj_set_x(ui_Button8otp, -88);
    lv_obj_set_y(ui_Button8otp, 48);
    lv_obj_set_align(ui_Button8otp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8otp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8otp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button8otp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button8otp, lv_color_hex(0x908B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button8otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button8otp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Button8otp);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "8");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &ui_font_Fontsim, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7otp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_Button7otp, 120);
    lv_obj_set_height(ui_Button7otp, 85);
    lv_obj_set_x(ui_Button7otp, -221);
    lv_obj_set_y(ui_Button7otp, 48);
    lv_obj_set_align(ui_Button7otp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7otp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7otp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7otp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button7otp, lv_color_hex(0x908B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button7otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button7otp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Button7otp);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "7");
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label33, &ui_font_Fontsim, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6otp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_Button6otp, 120);
    lv_obj_set_height(ui_Button6otp, 85);
    lv_obj_set_x(ui_Button6otp, 51);
    lv_obj_set_y(ui_Button6otp, -45);
    lv_obj_set_align(ui_Button6otp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6otp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6otp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6otp, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button6otp, lv_color_hex(0x908B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button6otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button6otp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_Button6otp);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "6");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label34, &ui_font_Fontsim, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5otp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_Button5otp, 120);
    lv_obj_set_height(ui_Button5otp, 85);
    lv_obj_set_x(ui_Button5otp, -88);
    lv_obj_set_y(ui_Button5otp, -45);
    lv_obj_set_align(ui_Button5otp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5otp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5otp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5otp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button5otp, lv_color_hex(0x908B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button5otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button5otp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_Button5otp);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "5");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &ui_font_Fontsim, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4otp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_Button4otp, 120);
    lv_obj_set_height(ui_Button4otp, 85);
    lv_obj_set_x(ui_Button4otp, -221);
    lv_obj_set_y(ui_Button4otp, -45);
    lv_obj_set_align(ui_Button4otp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4otp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4otp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4otp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button4otp, lv_color_hex(0x908B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button4otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button4otp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_Button4otp);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "4");
    lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label36, &ui_font_Fontsim, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3otp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_Button3otp, 120);
    lv_obj_set_height(ui_Button3otp, 85);
    lv_obj_set_x(ui_Button3otp, 51);
    lv_obj_set_y(ui_Button3otp, -138);
    lv_obj_set_align(ui_Button3otp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3otp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3otp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3otp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button3otp, lv_color_hex(0x908B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button3otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button3otp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_Button3otp);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "3");
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &ui_font_Fontsim, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1otp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_Button1otp, 120);
    lv_obj_set_height(ui_Button1otp, 85);
    lv_obj_set_x(ui_Button1otp, -221);
    lv_obj_set_y(ui_Button1otp, -138);
    lv_obj_set_align(ui_Button1otp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1otp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1otp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1otp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button1otp, lv_color_hex(0x908B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button1otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button1otp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_Button1otp);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "1");
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &ui_font_Fontsim, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttoncancelotp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_Buttoncancelotp, 130);
    lv_obj_set_height(ui_Buttoncancelotp, 85);
    lv_obj_set_x(ui_Buttoncancelotp, 192);
    lv_obj_set_y(ui_Buttoncancelotp, -138);
    lv_obj_set_align(ui_Buttoncancelotp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttoncancelotp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttoncancelotp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttoncancelotp, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttoncancelotp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttoncancelotp, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttoncancelotp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Buttoncancelotp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Buttoncancelotp);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "CANCEL");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &ui_font_Fontcan, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonclearotp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_Buttonclearotp, 130);
    lv_obj_set_height(ui_Buttonclearotp, 85);
    lv_obj_set_x(ui_Buttonclearotp, 192);
    lv_obj_set_y(ui_Buttonclearotp, -45);
    lv_obj_set_align(ui_Buttonclearotp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonclearotp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonclearotp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonclearotp, lv_color_hex(0xD2FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonclearotp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttonclearotp, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttonclearotp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Buttonclearotp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_Buttonclearotp);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "CLEAR");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label40, &ui_font_Fontcan, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonbackotp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_Buttonbackotp, 130);
    lv_obj_set_height(ui_Buttonbackotp, 85);
    lv_obj_set_x(ui_Buttonbackotp, 193);
    lv_obj_set_y(ui_Buttonbackotp, 141);
    lv_obj_set_align(ui_Buttonbackotp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonbackotp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonbackotp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonbackotp, lv_color_hex(0xFF5D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonbackotp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttonbackotp, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttonbackotp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Buttonbackotp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Buttonbackotp);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "<<");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &ui_font_Fontbsm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hashButtonotp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_hashButtonotp, 120);
    lv_obj_set_height(ui_hashButtonotp, 85);
    lv_obj_set_x(ui_hashButtonotp, -221);
    lv_obj_set_y(ui_hashButtonotp, 141);
    lv_obj_set_align(ui_hashButtonotp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hashButtonotp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_hashButtonotp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_hashButtonotp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hashButtonotp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_hashButtonotp, lv_color_hex(0x908B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_hashButtonotp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_hashButtonotp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_hashButtonotp);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "#");
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label42, &ui_font_Fontsim, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button0otp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_Button0otp, 120);
    lv_obj_set_height(ui_Button0otp, 80);
    lv_obj_set_x(ui_Button0otp, -88);
    lv_obj_set_y(ui_Button0otp, 141);
    lv_obj_set_align(ui_Button0otp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button0otp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button0otp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button0otp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button0otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button0otp, lv_color_hex(0x908B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button0otp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button0otp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_Button0otp);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "0");
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label43, &ui_font_Fontbsm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_starButtonotp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_starButtonotp, 120);
    lv_obj_set_height(ui_starButtonotp, 80);
    lv_obj_set_x(ui_starButtonotp, 51);
    lv_obj_set_y(ui_starButtonotp, 141);
    lv_obj_set_align(ui_starButtonotp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_starButtonotp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_starButtonotp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_starButtonotp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_starButtonotp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_starButtonotp, lv_color_hex(0x908B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_starButtonotp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_starButtonotp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_starButtonotp);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "*");
    lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label44, &ui_font_Fontsim, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonenterotp = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_Buttonenterotp, 130);
    lv_obj_set_height(ui_Buttonenterotp, 85);
    lv_obj_set_x(ui_Buttonenterotp, 192);
    lv_obj_set_y(ui_Buttonenterotp, 48);
    lv_obj_set_align(ui_Buttonenterotp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonenterotp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonenterotp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonenterotp, lv_color_hex(0x1AFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonenterotp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttonenterotp, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttonenterotp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Buttonenterotp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_Buttonenterotp);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "ENTER");
    lv_obj_set_style_text_color(ui_Label45, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label45, &ui_font_Fontcan, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2otp, ui_event_Button2otp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9otp, ui_event_Button9otp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8otp, ui_event_Button8otp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7otp, ui_event_Button7otp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6otp, ui_event_Button6otp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5otp, ui_event_Button5otp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4otp, ui_event_Button4otp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3otp, ui_event_Button3otp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1otp, ui_event_Button1otp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttoncancelotp, ui_event_Buttoncancelotp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonclearotp, ui_event_Buttonclearotp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonbackotp, ui_event_Buttonbackotp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_hashButtonotp, ui_event_hashButtonotp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button0otp, ui_event_Button0otp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_starButtonotp, ui_event_starButtonotp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonenterotp, ui_event_Buttonenterotp, LV_EVENT_ALL, NULL);

}
