// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: goldpe_arduino_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0xFFCA56), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen3, lv_color_hex(0xFF9A4E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen3, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 792);
    lv_obj_set_height(ui_Container3, 475);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Buttonnext3 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Buttonnext3, 120);
    lv_obj_set_height(ui_Buttonnext3, 120);
    lv_obj_set_x(ui_Buttonnext3, 294);
    lv_obj_set_y(ui_Buttonnext3, 150);
    lv_obj_set_align(ui_Buttonnext3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonnext3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonnext3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Buttonnext3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Buttonnext3, lv_color_hex(0xFF9D4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonnext3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttonnext3, lv_color_hex(0xEE1410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttonnext3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Buttonnext3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Buttonnext3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, ">>");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xEE1410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label8, -5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Fontb, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelaadhaar2 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Labelaadhaar2, 400);
    lv_obj_set_height(ui_Labelaadhaar2, 60);
    lv_obj_set_x(ui_Labelaadhaar2, 182);
    lv_obj_set_y(ui_Labelaadhaar2, -172);
    lv_obj_set_align(ui_Labelaadhaar2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelaadhaar2, "");
    lv_obj_set_style_text_align(ui_Labelaadhaar2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelaadhaar2, &ui_font_Fontbsm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonprev3 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Buttonprev3, 120);
    lv_obj_set_height(ui_Buttonprev3, 120);
    lv_obj_set_x(ui_Buttonprev3, -287);
    lv_obj_set_y(ui_Buttonprev3, 150);
    lv_obj_set_align(ui_Buttonprev3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonprev3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonprev3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Buttonprev3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Buttonprev3, lv_color_hex(0xFF9D4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonprev3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttonprev3, lv_color_hex(0xEE1410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttonprev3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Buttonprev3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Buttonprev3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "<<");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xEE1410), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label9, -5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Fontb, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaenterotp = lv_textarea_create(ui_Container3);
    lv_obj_set_width(ui_TextAreaenterotp, 397);
    lv_obj_set_height(ui_TextAreaenterotp, 70);
    lv_obj_set_x(ui_TextAreaenterotp, 184);
    lv_obj_set_y(ui_TextAreaenterotp, -80);
    lv_obj_set_align(ui_TextAreaenterotp, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaenterotp, "Enter 6 Digit OTP");
    lv_obj_set_style_text_font(ui_TextAreaenterotp, &ui_font_Fontsimsmall, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextAreaenterotp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextAreaenterotp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextAreaenterotp, 3, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_align(ui_TextAreaenterotp, LV_TEXT_ALIGN_AUTO, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaenterotp, &lv_font_montserrat_20,
                               LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -204);
    lv_obj_set_y(ui_Label10, -181);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "AADHAAR NUMBER");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Fontbsm, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -204);
    lv_obj_set_y(ui_Label11, -80);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "OTP");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Fontbsm, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Buttonnext3, ui_event_Buttonnext3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonprev3, ui_event_Buttonprev3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaenterotp, ui_event_TextAreaenterotp, LV_EVENT_ALL, NULL);

}
