// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: tft_Project

#ifndef _TFT_PROJECT_UI_H
#define _TFT_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_uidLabel;
extern lv_obj_t * ui_itemLabel;
extern lv_obj_t * ui_weightLabel;
extern lv_obj_t * ui_timeLabel;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_dateLabel;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_check_5610944_png);    // assets/check_5610944.png

// FONTS
LV_FONT_DECLARE(ui_font_Fontb);
LV_FONT_DECLARE(ui_font_Fontbsm);
LV_FONT_DECLARE(ui_font_Fontcan);
LV_FONT_DECLARE(ui_font_Fontnew);
LV_FONT_DECLARE(ui_font_Fontnum);
LV_FONT_DECLARE(ui_font_Fontsim);
LV_FONT_DECLARE(ui_font_Fontsimsmall);
LV_FONT_DECLARE(ui_font_Fontsmall);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
