// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: menu_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_inputButton(lv_event_t * e);
lv_obj_t * ui_inputButton;
lv_obj_t * ui_Label1;
void ui_event_outputButton(lv_event_t * e);
lv_obj_t * ui_outputButton;
lv_obj_t * ui_Label3;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
void ui_event_backButton(lv_event_t * e);
lv_obj_t * ui_backButton;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_adcvoltageLabel;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_adccurrentLabel;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Input1;
lv_obj_t * ui_Input2;
lv_obj_t * ui_Input3;
lv_obj_t * ui_Input4;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Labl1;
lv_obj_t * ui_Labl2;
lv_obj_t * ui_Labl3;
lv_obj_t * ui_Labl4;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
void ui_event_backButton1(lv_event_t * e);
lv_obj_t * ui_backButton1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_dacvoltageLabel;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_daccurrentLabel;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label15;
void ui_event_dacvoltageSlider(lv_event_t * e);
lv_obj_t * ui_dacvoltageSlider;
void ui_event_daccurrentSlider(lv_event_t * e);
lv_obj_t * ui_daccurrentSlider;
void ui_event_ledSwitch1(lv_event_t * e);
lv_obj_t * ui_ledSwitch1;
void ui_event_ledSwitch2(lv_event_t * e);
lv_obj_t * ui_ledSwitch2;
void ui_event_ledSwitch3(lv_event_t * e);
lv_obj_t * ui_ledSwitch3;
void ui_event_ledSwitch4(lv_event_t * e);
lv_obj_t * ui_ledSwitch4;
lv_obj_t * ui_Indicator1;
lv_obj_t * ui_Indicator2;
lv_obj_t * ui_Indicator3;
lv_obj_t * ui_Indicator4;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Labl9;
lv_obj_t * ui_Labl5;
lv_obj_t * ui_Labl6;
lv_obj_t * ui_Labl7;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_inputButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_outputButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_backButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_backButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_dacvoltageSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_dacvoltageLabel, target, "", "");
    }
}
void ui_event_daccurrentSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_daccurrentLabel, target, "", "");
    }
}
void ui_event_ledSwitch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        led_event1(e);
        _ui_state_modify(ui_Indicator1, LV_STATE_USER_1, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_ledSwitch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        led_event1(e);
        _ui_state_modify(ui_Indicator2, LV_STATE_USER_1, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_ledSwitch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        led_event1(e);
        _ui_state_modify(ui_Indicator3, LV_STATE_USER_1, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_ledSwitch4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        led_event1(e);
        _ui_state_modify(ui_Indicator4, LV_STATE_USER_1, _UI_MODIFY_STATE_TOGGLE);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
