// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: menu_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backButton1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_backButton1, 80);
    lv_obj_set_height(ui_backButton1, 80);
    lv_obj_set_x(ui_backButton1, 352);
    lv_obj_set_y(ui_backButton1, 193);
    lv_obj_set_align(ui_backButton1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_backButton1, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_backButton1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_backButton1, lv_color_hex(0x334755), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_backButton1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "PREV");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -2);
    lv_obj_set_y(ui_Label11, -207);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "OUTPUT");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel5, 150);
    lv_obj_set_height(ui_Panel5, 80);
    lv_obj_set_x(ui_Panel5, -127);
    lv_obj_set_y(ui_Panel5, -100);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel5, LV_SCROLLBAR_MODE_OFF);

    ui_dacvoltageLabel = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_dacvoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dacvoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dacvoltageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dacvoltageLabel, "0");
    lv_obj_set_style_text_font(ui_dacvoltageLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel6, 150);
    lv_obj_set_height(ui_Panel6, 80);
    lv_obj_set_x(ui_Panel6, 229);
    lv_obj_set_y(ui_Panel6, -100);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel6, LV_SCROLLBAR_MODE_OFF);

    ui_daccurrentLabel = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_daccurrentLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_daccurrentLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_daccurrentLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_daccurrentLabel, "0");
    lv_obj_set_style_text_font(ui_daccurrentLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -286);
    lv_obj_set_y(ui_Label14, -100);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "VOLTAGE");
    lv_obj_set_scrollbar_mode(ui_Label14, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 59);
    lv_obj_set_y(ui_Label15, -100);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "CURRENT");
    lv_obj_set_scrollbar_mode(ui_Label15, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dacvoltageSlider = lv_slider_create(ui_Screen3);
    lv_slider_set_range(ui_dacvoltageSlider, 0, 10);
    lv_slider_set_value(ui_dacvoltageSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_dacvoltageSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_dacvoltageSlider, 1,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_dacvoltageSlider, 300);
    lv_obj_set_height(ui_dacvoltageSlider, 28);
    lv_obj_set_x(ui_dacvoltageSlider, -175);
    lv_obj_set_y(ui_dacvoltageSlider, 5);
    lv_obj_set_align(ui_dacvoltageSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_dacvoltageSlider, lv_color_hex(0x463F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dacvoltageSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_dacvoltageSlider, lv_color_hex(0x373030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_dacvoltageSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_dacvoltageSlider, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_dacvoltageSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_dacvoltageSlider, lv_color_hex(0x37B9F5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dacvoltageSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_dacvoltageSlider, lv_color_hex(0x1464F0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_dacvoltageSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_dacvoltageSlider, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_dacvoltageSlider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_dacvoltageSlider, lv_color_hex(0x5F6464), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dacvoltageSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_dacvoltageSlider, lv_color_hex(0x3C424B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_dacvoltageSlider, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_dacvoltageSlider, lv_color_hex(0x373C46), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_dacvoltageSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_dacvoltageSlider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_dacvoltageSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_dacvoltageSlider, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_dacvoltageSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dacvoltageSlider, 20, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dacvoltageSlider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_dacvoltageSlider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_dacvoltageSlider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_dacvoltageSlider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_dacvoltageSlider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dacvoltageSlider, lv_color_hex(0x827C7C), LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_dacvoltageSlider, 255, LV_PART_KNOB | LV_STATE_PRESSED);

    ui_daccurrentSlider = lv_slider_create(ui_Screen3);
    lv_slider_set_range(ui_daccurrentSlider, 4, 20);
    lv_slider_set_value(ui_daccurrentSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_daccurrentSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_daccurrentSlider, 1,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_daccurrentSlider, 300);
    lv_obj_set_height(ui_daccurrentSlider, 28);
    lv_obj_set_x(ui_daccurrentSlider, 207);
    lv_obj_set_y(ui_daccurrentSlider, 3);
    lv_obj_set_align(ui_daccurrentSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_daccurrentSlider, lv_color_hex(0x463F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_daccurrentSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_daccurrentSlider, lv_color_hex(0x373030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_daccurrentSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_daccurrentSlider, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_daccurrentSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_daccurrentSlider, lv_color_hex(0x37B9F5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_daccurrentSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_daccurrentSlider, lv_color_hex(0x1464F0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_daccurrentSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_daccurrentSlider, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_daccurrentSlider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_daccurrentSlider, lv_color_hex(0x5F6464), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_daccurrentSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_daccurrentSlider, lv_color_hex(0x3C424B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_daccurrentSlider, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_daccurrentSlider, lv_color_hex(0x373C46), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_daccurrentSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_daccurrentSlider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_daccurrentSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_daccurrentSlider, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_daccurrentSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_daccurrentSlider, 20, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_daccurrentSlider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_daccurrentSlider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_daccurrentSlider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_daccurrentSlider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_daccurrentSlider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_daccurrentSlider, lv_color_hex(0x827C7C), LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_daccurrentSlider, 255, LV_PART_KNOB | LV_STATE_PRESSED);

    ui_ledSwitch1 = lv_switch_create(ui_Screen3);
    lv_obj_set_width(ui_ledSwitch1, 70);
    lv_obj_set_height(ui_ledSwitch1, 40);
    lv_obj_set_x(ui_ledSwitch1, -250);
    lv_obj_set_y(ui_ledSwitch1, 114);
    lv_obj_set_align(ui_ledSwitch1, LV_ALIGN_CENTER);


    ui_ledSwitch2 = lv_switch_create(ui_Screen3);
    lv_obj_set_width(ui_ledSwitch2, 70);
    lv_obj_set_height(ui_ledSwitch2, 40);
    lv_obj_set_x(ui_ledSwitch2, -68);
    lv_obj_set_y(ui_ledSwitch2, 114);
    lv_obj_set_align(ui_ledSwitch2, LV_ALIGN_CENTER);


    ui_ledSwitch3 = lv_switch_create(ui_Screen3);
    lv_obj_set_width(ui_ledSwitch3, 70);
    lv_obj_set_height(ui_ledSwitch3, 40);
    lv_obj_set_x(ui_ledSwitch3, 114);
    lv_obj_set_y(ui_ledSwitch3, 114);
    lv_obj_set_align(ui_ledSwitch3, LV_ALIGN_CENTER);


    ui_ledSwitch4 = lv_switch_create(ui_Screen3);
    lv_obj_set_width(ui_ledSwitch4, 70);
    lv_obj_set_height(ui_ledSwitch4, 40);
    lv_obj_set_x(ui_ledSwitch4, 296);
    lv_obj_set_y(ui_ledSwitch4, 114);
    lv_obj_set_align(ui_ledSwitch4, LV_ALIGN_CENTER);


    ui_Indicator1 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Indicator1, 40);
    lv_obj_set_height(ui_Indicator1, 40);
    lv_obj_set_x(ui_Indicator1, -322);
    lv_obj_set_y(ui_Indicator1, 114);
    lv_obj_set_align(ui_Indicator1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Indicator1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Indicator1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Indicator1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Indicator1, lv_color_hex(0x37D866), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_Indicator1, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_Indicator1, lv_color_hex(0x26A93E), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_Indicator1, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_Indicator2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Indicator2, 40);
    lv_obj_set_height(ui_Indicator2, 40);
    lv_obj_set_x(ui_Indicator2, -140);
    lv_obj_set_y(ui_Indicator2, 114);
    lv_obj_set_align(ui_Indicator2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Indicator2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Indicator2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Indicator2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Indicator2, lv_color_hex(0x37D866), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_Indicator2, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_Indicator2, lv_color_hex(0x26A93E), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_Indicator2, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_Indicator3 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Indicator3, 40);
    lv_obj_set_height(ui_Indicator3, 40);
    lv_obj_set_x(ui_Indicator3, 42);
    lv_obj_set_y(ui_Indicator3, 114);
    lv_obj_set_align(ui_Indicator3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Indicator3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Indicator3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Indicator3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Indicator3, lv_color_hex(0x37D866), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_Indicator3, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_Indicator3, lv_color_hex(0x26A93E), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_Indicator3, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_Indicator4 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Indicator4, 40);
    lv_obj_set_height(ui_Indicator4, 40);
    lv_obj_set_x(ui_Indicator4, 224);
    lv_obj_set_y(ui_Indicator4, 114);
    lv_obj_set_align(ui_Indicator4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Indicator4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Indicator4, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Indicator4, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Indicator4, lv_color_hex(0x37D866), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_Indicator4, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_Indicator4, lv_color_hex(0x26A93E), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_Indicator4, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_Container4 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 664);
    lv_obj_set_height(ui_Container4, 21);
    lv_obj_set_x(ui_Container4, -18);
    lv_obj_set_y(ui_Container4, 163);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Container4, LV_SCROLLBAR_MODE_OFF);

    ui_Labl9 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Labl9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labl9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labl9, -69);
    lv_obj_set_y(ui_Labl9, -2);
    lv_obj_set_align(ui_Labl9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labl9, "1");
    lv_obj_set_style_text_color(ui_Labl9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labl9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labl9, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labl5 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Labl5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labl5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labl5, -33);
    lv_obj_set_y(ui_Labl5, -2);
    lv_obj_set_align(ui_Labl5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labl5, "2");
    lv_obj_set_style_text_font(ui_Labl5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labl6 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Labl6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labl6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labl6, 23);
    lv_obj_set_y(ui_Labl6, -5);
    lv_obj_set_align(ui_Labl6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labl6, "3");
    lv_obj_set_style_text_font(ui_Labl6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labl7 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Labl7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labl7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labl7, 103);
    lv_obj_set_y(ui_Labl7, -11);
    lv_obj_set_align(ui_Labl7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labl7, "4");
    lv_obj_set_style_text_font(ui_Labl7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backButton1, ui_event_backButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dacvoltageSlider, ui_event_dacvoltageSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_daccurrentSlider, ui_event_daccurrentSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ledSwitch1, ui_event_ledSwitch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ledSwitch2, ui_event_ledSwitch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ledSwitch3, ui_event_ledSwitch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ledSwitch4, ui_event_ledSwitch4, LV_EVENT_ALL, NULL);

}
