// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: menu_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Screen2, LV_SCROLLBAR_MODE_OFF);

    ui_backButton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_backButton, 80);
    lv_obj_set_height(ui_backButton, 80);
    lv_obj_set_x(ui_backButton, 352);
    lv_obj_set_y(ui_backButton, 193);
    lv_obj_set_align(ui_backButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_backButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_backButton, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_backButton, lv_color_hex(0x334755), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_backButton);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "PREV");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel1, 150);
    lv_obj_set_height(ui_Panel1, 80);
    lv_obj_set_x(ui_Panel1, -127);
    lv_obj_set_y(ui_Panel1, -100);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel1, LV_SCROLLBAR_MODE_OFF);

    ui_adcvoltageLabel = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_adcvoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_adcvoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_adcvoltageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_adcvoltageLabel, "0");
    lv_obj_set_style_text_font(ui_adcvoltageLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel2, 150);
    lv_obj_set_height(ui_Panel2, 80);
    lv_obj_set_x(ui_Panel2, 229);
    lv_obj_set_y(ui_Panel2, -100);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel2, LV_SCROLLBAR_MODE_OFF);

    ui_adccurrentLabel = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_adccurrentLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_adccurrentLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_adccurrentLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_adccurrentLabel, "0");
    lv_obj_set_style_text_font(ui_adccurrentLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -286);
    lv_obj_set_y(ui_Label2, -100);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "VOLTAGE");
    lv_obj_set_scrollbar_mode(ui_Label2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 59);
    lv_obj_set_y(ui_Label7, -100);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "CURRENT");
    lv_obj_set_scrollbar_mode(ui_Label7, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -2);
    lv_obj_set_y(ui_Label9, -207);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "INPUT");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 441);
    lv_obj_set_height(ui_Container1, 123);
    lv_obj_set_x(ui_Container1, 11);
    lv_obj_set_y(ui_Container1, 70);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Container1, LV_SCROLLBAR_MODE_OFF);

    ui_Input1 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Input1, 100);
    lv_obj_set_height(ui_Input1, 70);
    lv_obj_set_x(ui_Input1, -20);
    lv_obj_set_y(ui_Input1, 1);
    lv_obj_set_align(ui_Input1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Input1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Input1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Input1, lv_color_hex(0x373434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Input1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Input2 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Input2, 100);
    lv_obj_set_height(ui_Input2, 70);
    lv_obj_set_x(ui_Input2, -64);
    lv_obj_set_y(ui_Input2, 2);
    lv_obj_set_align(ui_Input2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Input2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Input2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Input2, lv_color_hex(0x373434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Input2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Input3 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Input3, 100);
    lv_obj_set_height(ui_Input3, 70);
    lv_obj_set_x(ui_Input3, 30);
    lv_obj_set_y(ui_Input3, 0);
    lv_obj_set_align(ui_Input3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Input3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Input3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Input3, lv_color_hex(0x373434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Input3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Input4 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Input4, 100);
    lv_obj_set_height(ui_Input4, 70);
    lv_obj_set_x(ui_Input4, 80);
    lv_obj_set_y(ui_Input4, 0);
    lv_obj_set_align(ui_Input4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Input4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Input4, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Input4, lv_color_hex(0x373434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Input4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 410);
    lv_obj_set_height(ui_Container3, 21);
    lv_obj_set_x(ui_Container3, 12);
    lv_obj_set_y(ui_Container3, 143);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Container3, LV_SCROLLBAR_MODE_OFF);

    ui_Labl1 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Labl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labl1, -69);
    lv_obj_set_y(ui_Labl1, -2);
    lv_obj_set_align(ui_Labl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labl1, "1");
    lv_obj_set_style_text_color(ui_Labl1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labl1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labl2 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Labl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labl2, -33);
    lv_obj_set_y(ui_Labl2, -2);
    lv_obj_set_align(ui_Labl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labl2, "2");
    lv_obj_set_style_text_font(ui_Labl2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labl3 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Labl3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labl3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labl3, 23);
    lv_obj_set_y(ui_Labl3, -5);
    lv_obj_set_align(ui_Labl3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labl3, "3");
    lv_obj_set_style_text_font(ui_Labl3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labl4 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Labl4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labl4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labl4, 73);
    lv_obj_set_y(ui_Labl4, -5);
    lv_obj_set_align(ui_Labl4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labl4, "4");
    lv_obj_set_style_text_font(ui_Labl4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backButton, ui_event_backButton, LV_EVENT_ALL, NULL);

}
