// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: warehouse_qr

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_timeLabel;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_weightLabel;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
void ui_event_clearButton(lv_event_t * e);
lv_obj_t * ui_clearButton;
lv_obj_t * ui_Label9;
void ui_event_submitButton(lv_event_t * e);
lv_obj_t * ui_submitButton;
lv_obj_t * ui_Label10;
void ui_event_opidTextArea(lv_event_t * e);
lv_obj_t * ui_opidTextArea;
void ui_event_regionTextArea(lv_event_t * e);
lv_obj_t * ui_regionTextArea;
void ui_event_fnameTextArea(lv_event_t * e);
lv_obj_t * ui_fnameTextArea;
void ui_event_fidTextArea(lv_event_t * e);
lv_obj_t * ui_fidTextArea;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_qrLabel;
lv_obj_t * ui_Label11;
// CUSTOM VARIABLES


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Container2;
lv_obj_t * ui_TextArea;
void ui_event_Keyboard(lv_event_t * e);
lv_obj_t * ui_Keyboard;
// CUSTOM VARIABLES
lv_obj_t* previous_screen = NULL;
lv_obj_t* active_textarea = NULL;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_clearButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        on_clear(e);
    }
}

void ui_event_submitButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        on_submit(e);
    }
}

void ui_event_opidTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_textarea_set_cursor_click_pos(ui_opidTextArea, false);
    lv_obj_clear_state(ui_opidTextArea, LV_STATE_FOCUSED); 

    if(event_code == LV_EVENT_PRESSED) {
        active_textarea = lv_event_get_target(e);
        previous_screen = lv_scr_act();
        lv_scr_load(ui_Screen2);
        // _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_regionTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_textarea_set_cursor_click_pos(ui_regionTextArea, false);
    lv_obj_clear_state(ui_regionTextArea, LV_STATE_FOCUSED);

    if(event_code == LV_EVENT_PRESSED) {
        active_textarea = lv_event_get_target(e);
        previous_screen = lv_scr_act();
        lv_scr_load(ui_Screen2);
        // _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_fnameTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_textarea_set_cursor_click_pos(ui_fnameTextArea, false);
    lv_obj_clear_state(ui_fnameTextArea, LV_STATE_FOCUSED);

    if(event_code == LV_EVENT_PRESSED) {
        active_textarea = lv_event_get_target(e);
        previous_screen = lv_scr_act();
        lv_scr_load(ui_Screen2);
        // _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_fidTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_textarea_set_cursor_click_pos(ui_fidTextArea, false);
    lv_obj_clear_state(ui_fidTextArea, LV_STATE_FOCUSED);

    if(event_code == LV_EVENT_PRESSED) {
        active_textarea = lv_event_get_target(e);
        previous_screen = lv_scr_act();
        lv_scr_load(ui_Screen2);
        // _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        get_data(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
