// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: warehouse_qr

#include "ui.h"

bool data = false;
bool clear = false;
bool submit = false;

void on_clear(lv_event_t * e)
{
	clear = true;
}

void on_submit(lv_event_t * e)
{
	submit = true;
}

void get_data(lv_event_t * e)
{
	data = true;
}
