// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: warehouse_qr

#include "ui.h"

static void ui_event_Key(lv_event_t * e);

static const char * custom_map[] = {
    "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "\n",
    "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", LV_SYMBOL_BACKSPACE, "\n",
    "ABC","a", "s", "d", "f", "g", "h", "j", "k", "l","\n",
    "z", "x", "c", "v", "b", "n", "m",  LV_SYMBOL_NEW_LINE, "\n",
    LV_SYMBOL_LEFT, " ", LV_SYMBOL_RIGHT, LV_SYMBOL_OK, ""
};

static const char * custom_map_cap[] = {
    "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "\n",
    "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", LV_SYMBOL_BACKSPACE, "\n",
    "abc","A", "S", "D", "F", "G", "H", "J", "K", "L", "\n",
    "Z", "X", "C", "V", "B", "N", "M", LV_SYMBOL_NEW_LINE, "\n",
    LV_SYMBOL_LEFT, " ", LV_SYMBOL_RIGHT, LV_SYMBOL_OK, ""
};

static const lv_btnmatrix_ctrl_t custom_ctrl_map[] = {
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT, 
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT, 
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT, 
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT, 
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT,

    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT,
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT, 
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT, 
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT, 
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT,
    LV_BTNMATRIX_CTRL_NO_REPEAT,  

    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT, 
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT, 
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT, 
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT, 
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT,  

    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT, 
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT, 
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT, 
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT,

    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT, 
    LV_BTNMATRIX_CTRL_NO_REPEAT, LV_BTNMATRIX_CTRL_NO_REPEAT,  
};

static void ui_event_Key(lv_event_t * e)
{
    lv_obj_t * keyboard_obj = lv_event_get_target(e);
    lv_keyboard_t * keyboard = (lv_keyboard_t *)keyboard_obj;

    lv_textarea_t * ta = (lv_textarea_t *)keyboard->ta;
    if (ta == NULL) return;

    uint16_t btn_id   = lv_btnmatrix_get_selected_btn(keyboard_obj);
    if(btn_id == LV_BTNMATRIX_BTN_NONE) return;

    const char * txt = lv_btnmatrix_get_btn_text(keyboard_obj, btn_id);
    if(txt == NULL) return;
    
    if(strcmp(txt, "abc") == 0) 
    {
        lv_keyboard_set_map(keyboard_obj, LV_KEYBOARD_MODE_USER_1, custom_map, custom_ctrl_map);
        lv_keyboard_set_mode(keyboard_obj, LV_KEYBOARD_MODE_USER_1);
        return;
    }

    else if(strcmp(txt, "ABC") == 0) 
    {
        lv_keyboard_set_map(keyboard_obj, LV_KEYBOARD_MODE_USER_2, custom_map_cap, custom_ctrl_map);
        lv_keyboard_set_mode(keyboard_obj, LV_KEYBOARD_MODE_USER_2);
        return;
    }

    else if(strcmp(txt, LV_SYMBOL_OK) == 0) 
    {
        lv_res_t res = lv_event_send(keyboard_obj, LV_EVENT_READY, NULL);
        if(res != LV_RES_OK) return;

        if(ta) 
        {
            res = lv_event_send((lv_obj_t *)ta, LV_EVENT_READY, NULL);
            if(res != LV_RES_OK) return;
        }

        lv_scr_load(ui_Screen1);
        lv_textarea_set_cursor_click_pos((lv_obj_t *)ta, false); // Hide the cursor
        lv_obj_clear_state((lv_obj_t *)ta, LV_STATE_FOCUSED); 

        lv_textarea_set_cursor_click_pos(ui_opidTextArea, false); // Hide the cursor
        lv_obj_clear_state(ui_opidTextArea, LV_STATE_FOCUSED); 

        lv_textarea_set_cursor_click_pos(ui_regionTextArea, false);
        lv_obj_clear_state(ui_regionTextArea, LV_STATE_FOCUSED);

        lv_textarea_set_cursor_click_pos(ui_fnameTextArea, false);
        lv_obj_clear_state(ui_fnameTextArea, LV_STATE_FOCUSED);

        lv_textarea_set_cursor_click_pos(ui_fidTextArea, false);
        lv_obj_clear_state(ui_fidTextArea, LV_STATE_FOCUSED);

        return;
    }
    else if(strcmp(txt, LV_SYMBOL_NEW_LINE) == 0)
    {
        lv_textarea_add_char((lv_obj_t *)ta, '\n');
    }
    else if(strcmp(txt, LV_SYMBOL_LEFT) == 0) 
    {
        lv_textarea_cursor_left((lv_obj_t *)ta);
    }
    else if(strcmp(txt, LV_SYMBOL_RIGHT) == 0) 
    {
        lv_textarea_cursor_right((lv_obj_t *)ta);
    }
    else if(strcmp(txt, LV_SYMBOL_BACKSPACE) == 0) 
    {
        lv_textarea_del_char((lv_obj_t *)ta);
    }

    else 
    {
        lv_textarea_add_text((lv_obj_t *)ta, txt);
    }
    
}


void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xD3CA85), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 784);
    lv_obj_set_height(ui_Container2, 472);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea = lv_textarea_create(ui_Container2);
    lv_obj_set_width(ui_TextArea, 767);
    lv_obj_set_height(ui_TextArea, 65);
    lv_obj_set_x(ui_TextArea, 0);
    lv_obj_set_y(ui_TextArea, -152);
    lv_obj_set_align(ui_TextArea, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_TextArea, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Keyboard = lv_keyboard_create(ui_Container2);
    lv_obj_set_width(ui_Keyboard, 790);
    lv_obj_set_height(ui_Keyboard, 300);
    lv_obj_set_x(ui_Keyboard, 0);
    lv_obj_set_y(ui_Keyboard, 66);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Keyboard, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0xD5CA83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Keyboard, 15, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Keyboard, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Keyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Keyboard, &lv_font_montserrat_20, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_keyboard_set_map(ui_Keyboard, LV_KEYBOARD_MODE_USER_2, custom_map_cap, custom_ctrl_map);
    lv_keyboard_set_mode(ui_Keyboard, LV_KEYBOARD_MODE_USER_2);

    lv_obj_remove_event_cb(ui_Keyboard, lv_keyboard_def_event_cb);

    // lv_obj_add_event_cb(ui_Keyboard, ui_event_TextArea, LV_EVENT_ALL, NULL);
    // lv_keyboard_set_textarea(ui_Keyboard, ui_TextArea);
    
    lv_obj_add_event_cb(ui_Keyboard, ui_event_Key, LV_EVENT_CLICKED, NULL);

    lv_keyboard_set_textarea(ui_Keyboard, ui_TextArea);
    lv_obj_add_event_cb(ui_Keyboard, ui_event_Keyboard, LV_EVENT_ALL, NULL);

}
