// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: IOI_Project

#include "ui.h"
bool slider_voltage = false;
bool slider_current = false;
bool led1 ;
// void led_event4(lv_event_t * e)
// {
// 	// Your code here
// }

void led_event3(lv_event_t * e)
{
	// Your code here
}

void led_event2(lv_event_t * e)
{
	// Your code here
}

void led_event1(lv_event_t * e)
{
	// Your code here
}
void ledoff1(lv_event_t * e)
{
  led1 = false;
  printf("led off \n");
}

void ledon1(lv_event_t * e)
{
  led1 = true;
  printf("led on \n");
}

void sldr_current_dac(lv_event_t * e)
{
	slider_current = true;
	
}

void sldr_voltage_dac(lv_event_t * e)
{
	slider_voltage = true;
}
