// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: IOI_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif
extern bool led1;
extern bool led2;
extern bool slider_voltage;
//extern bool slider_current;
//void led_event4(lv_event_t * e);
void led_event3(lv_event_t * e);
void led_event2(lv_event_t * e);
//void led_event1(lv_event_t * e);
void sldr_current_dac(lv_event_t * e);
void sldr_voltage_dac(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
