// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: IOI_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 786);
    lv_obj_set_height(ui_Container3, 461);
    lv_obj_set_x(ui_Container3, 1);
    lv_obj_set_y(ui_Container3, 0);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container4 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 410);
    lv_obj_set_height(ui_Container4, 21);
    lv_obj_set_x(ui_Container4, 12);
    lv_obj_set_y(ui_Container4, 143);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Container4, LV_SCROLLBAR_MODE_OFF);

    ui_Labl5 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Labl5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labl5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labl5, -69);
    lv_obj_set_y(ui_Labl5, -2);
    lv_obj_set_align(ui_Labl5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labl5, "1");
    lv_obj_set_style_text_color(ui_Labl5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labl5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labl5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labl6 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Labl6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labl6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labl6, -33);
    lv_obj_set_y(ui_Labl6, -2);
    lv_obj_set_align(ui_Labl6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labl6, "2");
    lv_obj_set_style_text_font(ui_Labl6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labl7 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Labl7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labl7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labl7, 23);
    lv_obj_set_y(ui_Labl7, -5);
    lv_obj_set_align(ui_Labl7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labl7, "3");
    lv_obj_set_style_text_font(ui_Labl7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labl8 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Labl8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labl8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labl8, 73);
    lv_obj_set_y(ui_Labl8, -5);
    lv_obj_set_align(ui_Labl8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labl8, "4");
    lv_obj_set_style_text_font(ui_Labl8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 441);
    lv_obj_set_height(ui_Container5, 123);
    lv_obj_set_x(ui_Container5, 11);
    lv_obj_set_y(ui_Container5, 70);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Container5, LV_SCROLLBAR_MODE_OFF);

    ui_Input1 = lv_obj_create(ui_Container5);
    lv_obj_set_width(ui_Input1, 100);
    lv_obj_set_height(ui_Input1, 70);
    lv_obj_set_x(ui_Input1, -20);
    lv_obj_set_y(ui_Input1, 1);
    lv_obj_set_align(ui_Input1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Input1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Input1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Input1, lv_color_hex(0x373434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Input1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Input2 = lv_obj_create(ui_Container5);
    lv_obj_set_width(ui_Input2, 100);
    lv_obj_set_height(ui_Input2, 70);
    lv_obj_set_x(ui_Input2, -64);
    lv_obj_set_y(ui_Input2, 2);
    lv_obj_set_align(ui_Input2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Input2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Input2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Input2, lv_color_hex(0x373434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Input2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Input3 = lv_obj_create(ui_Container5);
    lv_obj_set_width(ui_Input3, 100);
    lv_obj_set_height(ui_Input3, 70);
    lv_obj_set_x(ui_Input3, 30);
    lv_obj_set_y(ui_Input3, 0);
    lv_obj_set_align(ui_Input3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Input3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Input3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Input3, lv_color_hex(0x373434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Input3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Input4 = lv_obj_create(ui_Container5);
    lv_obj_set_width(ui_Input4, 100);
    lv_obj_set_height(ui_Input4, 70);
    lv_obj_set_x(ui_Input4, 80);
    lv_obj_set_y(ui_Input4, 0);
    lv_obj_set_align(ui_Input4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Input4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Input4, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Input4, lv_color_hex(0x373434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Input4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel5, 150);
    lv_obj_set_height(ui_Panel5, 80);
    lv_obj_set_x(ui_Panel5, 229);
    lv_obj_set_y(ui_Panel5, -100);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel5, LV_SCROLLBAR_MODE_OFF);

    ui_adccurrentLabel2 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_adccurrentLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_adccurrentLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_adccurrentLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_adccurrentLabel2, "0");
    lv_obj_set_style_text_font(ui_adccurrentLabel2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -2);
    lv_obj_set_y(ui_Label5, -207);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "INPUT");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 59);
    lv_obj_set_y(ui_Label6, -100);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "CURRENT");
    lv_obj_set_scrollbar_mode(ui_Label6, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -286);
    lv_obj_set_y(ui_Label7, -100);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "VOLTAGE");
    lv_obj_set_scrollbar_mode(ui_Label7, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel3, 150);
    lv_obj_set_height(ui_Panel3, 80);
    lv_obj_set_x(ui_Panel3, -127);
    lv_obj_set_y(ui_Panel3, -100);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel3, LV_SCROLLBAR_MODE_OFF);

    ui_adcvoltageLabel2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_adcvoltageLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_adcvoltageLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_adcvoltageLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_adcvoltageLabel2, "0");
    lv_obj_set_style_text_font(ui_adcvoltageLabel2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backButton3 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_backButton3, 80);
    lv_obj_set_height(ui_backButton3, 80);
    lv_obj_set_x(ui_backButton3, 352);
    lv_obj_set_y(ui_backButton3, 193);
    lv_obj_set_align(ui_backButton3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_backButton3, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_backButton3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_backButton3, lv_color_hex(0x334755), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_backButton3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "O/P");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backButton3, ui_event_backButton3, LV_EVENT_ALL, NULL);

}
