// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SQ_tft

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Container1;
void ui_event_HomeButton1(lv_event_t * e);
lv_obj_t * ui_HomeButton1;
lv_obj_t * ui_Label10;
void ui_event_TempButton1(lv_event_t * e);
lv_obj_t * ui_TempButton1;
lv_obj_t * ui_Label1;
void ui_event_HumButton1(lv_event_t * e);
lv_obj_t * ui_HumButton1;
lv_obj_t * ui_Label2;
void ui_event_InputButton1(lv_event_t * e);
lv_obj_t * ui_InputButton1;
lv_obj_t * ui_Label3;
void ui_event_OutputButton1(lv_event_t * e);
lv_obj_t * ui_OutputButton1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Container2;
lv_obj_t * ui_TempPanel;
lv_obj_t * ui_Tempvalue;
lv_obj_t * ui_HumPanel;
lv_obj_t * ui_Humvalue;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label7;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Container4;
void ui_event_HomeButton2(lv_event_t * e);
lv_obj_t * ui_HomeButton2;
lv_obj_t * ui_Label25;
void ui_event_TempButton2(lv_event_t * e);
lv_obj_t * ui_TempButton2;
lv_obj_t * ui_Label11;
void ui_event_HumButton2(lv_event_t * e);
lv_obj_t * ui_HumButton2;
lv_obj_t * ui_Label6;
void ui_event_InputButton2(lv_event_t * e);
lv_obj_t * ui_InputButton2;
lv_obj_t * ui_Label8;
void ui_event_OutputButton2(lv_event_t * e);
lv_obj_t * ui_OutputButton2;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Temp_Panel;
lv_obj_t * ui_tempvalue;
lv_obj_t * ui_TempChart;
lv_obj_t * ui_Label24;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Container5;
void ui_event_HomeButton3(lv_event_t * e);
lv_obj_t * ui_HomeButton3;
lv_obj_t * ui_Label26;
void ui_event_TemButton3(lv_event_t * e);
lv_obj_t * ui_TemButton3;
lv_obj_t * ui_Label12;
void ui_event_HumButton3(lv_event_t * e);
lv_obj_t * ui_HumButton3;
lv_obj_t * ui_Label13;
void ui_event_InputButton3(lv_event_t * e);
lv_obj_t * ui_InputButton3;
lv_obj_t * ui_Label14;
void ui_event_OutputButton3(lv_event_t * e);
lv_obj_t * ui_OutputButton3;
lv_obj_t * ui_Label15;
lv_obj_t * ui_HumChart;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Hum_Panel;
lv_obj_t * ui_humvalue;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_Container6;
void ui_event_HomeButton4(lv_event_t * e);
lv_obj_t * ui_HomeButton4;
lv_obj_t * ui_Label27;
void ui_event_TempButton4(lv_event_t * e);
lv_obj_t * ui_TempButton4;
lv_obj_t * ui_Label16;
void ui_event_HumButton4(lv_event_t * e);
lv_obj_t * ui_HumButton4;
lv_obj_t * ui_Label17;
void ui_event_InputButton4(lv_event_t * e);
lv_obj_t * ui_InputButton4;
lv_obj_t * ui_Label18;
void ui_event_OutputButton4(lv_event_t * e);
lv_obj_t * ui_OutputButton4;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Input1;
lv_obj_t * ui_Input2;
lv_obj_t * ui_Input3;
lv_obj_t * ui_Input4;
lv_obj_t * ui_Container8;
lv_obj_t * ui_Labl1;
lv_obj_t * ui_Labl2;
lv_obj_t * ui_Labl3;
lv_obj_t * ui_Labl4;


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t * ui_Screen5;
lv_obj_t * ui_Container7;
void ui_event_HomeButton5(lv_event_t * e);
lv_obj_t * ui_HomeButton5;
lv_obj_t * ui_Label28;
void ui_event_TempButton5(lv_event_t * e);
lv_obj_t * ui_TempButton5;
lv_obj_t * ui_Label20;
void ui_event_HumButton5(lv_event_t * e);
lv_obj_t * ui_HumButton5;
lv_obj_t * ui_Label21;
void ui_event_InputButton5(lv_event_t * e);
lv_obj_t * ui_InputButton5;
lv_obj_t * ui_Label22;
void ui_event_OutputButton5(lv_event_t * e);
lv_obj_t * ui_OutputButton5;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Container9;
void ui_event_ledSwitch2(lv_event_t * e);
lv_obj_t * ui_ledSwitch2;
void ui_event_ledSwitch3(lv_event_t * e);
lv_obj_t * ui_ledSwitch3;
void ui_event_ledSwitch4(lv_event_t * e);
lv_obj_t * ui_ledSwitch4;
void ui_event_ledSwitch1(lv_event_t * e);
lv_obj_t * ui_ledSwitch1;
lv_obj_t * ui_Indicator1;
lv_obj_t * ui_Indicator2;
lv_obj_t * ui_Indicator3;
lv_obj_t * ui_Indicator4;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_HomeButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_TempButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_HumButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_InputButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen4_screen_init);
    }
}
void ui_event_OutputButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen5_screen_init);
    }
}
void ui_event_HomeButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_TempButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_HumButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_InputButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen4_screen_init);
    }
}
void ui_event_OutputButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen5_screen_init);
    }
}
void ui_event_HomeButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_TemButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_HumButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_InputButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen4_screen_init);
    }
}
void ui_event_OutputButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen5_screen_init);
    }
}
void ui_event_HomeButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_TempButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_HumButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_InputButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen4_screen_init);
    }
}
void ui_event_OutputButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen5_screen_init);
    }
}
void ui_event_HomeButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_TempButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_HumButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_InputButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen4_screen_init);
    }
}
void ui_event_OutputButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_Screen5_screen_init);
    }
}
void ui_event_ledSwitch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        //led_event2(e);
        bool state = lv_obj_has_state(target, LV_STATE_CHECKED);
        // printf("Event code: %d\n", state);
        
        if (state == 0)
        {
            ledon2(e);
        }
        else
        {
            ledoff2(e);
        }
    }
}
void ui_event_ledSwitch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        led_event3(e);
    }
}
void ui_event_ledSwitch4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        led_event4(e);
    }
}
void ui_event_ledSwitch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        //led__event1(e);
        bool state = lv_obj_has_state(target, LV_STATE_CHECKED);
        // printf("Event code: %d\n", state);
        printf("inside the event \n");
        if (state == 0)
        {
            ledon1(e);
        }
        else
        {
            ledoff1(e);
        }
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
