// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SQ_tft

#ifndef _SQ_TFT_UI_H
#define _SQ_TFT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
void ui_event_HomeButton1(lv_event_t * e);
extern lv_obj_t * ui_HomeButton1;
extern lv_obj_t * ui_Label10;
void ui_event_TempButton1(lv_event_t * e);
extern lv_obj_t * ui_TempButton1;
extern lv_obj_t * ui_Label1;
void ui_event_HumButton1(lv_event_t * e);
extern lv_obj_t * ui_HumButton1;
extern lv_obj_t * ui_Label2;
void ui_event_InputButton1(lv_event_t * e);
extern lv_obj_t * ui_InputButton1;
extern lv_obj_t * ui_Label3;
void ui_event_OutputButton1(lv_event_t * e);
extern lv_obj_t * ui_OutputButton1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_TempPanel;
extern lv_obj_t * ui_Tempvalue;
extern lv_obj_t * ui_HumPanel;
extern lv_obj_t * ui_Humvalue;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label7;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container4;
void ui_event_HomeButton2(lv_event_t * e);
extern lv_obj_t * ui_HomeButton2;
extern lv_obj_t * ui_Label25;
void ui_event_TempButton2(lv_event_t * e);
extern lv_obj_t * ui_TempButton2;
extern lv_obj_t * ui_Label11;
void ui_event_HumButton2(lv_event_t * e);
extern lv_obj_t * ui_HumButton2;
extern lv_obj_t * ui_Label6;
void ui_event_InputButton2(lv_event_t * e);
extern lv_obj_t * ui_InputButton2;
extern lv_obj_t * ui_Label8;
void ui_event_OutputButton2(lv_event_t * e);
extern lv_obj_t * ui_OutputButton2;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Temp_Panel;
extern lv_obj_t * ui_tempvalue;
extern lv_obj_t * ui_TempChart;
extern lv_obj_t * ui_Label24;
extern lv_chart_series_t * ui_TempChart_series_1;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Container5;
void ui_event_HomeButton3(lv_event_t * e);
extern lv_obj_t * ui_HomeButton3;
extern lv_obj_t * ui_Label26;
void ui_event_TemButton3(lv_event_t * e);
extern lv_obj_t * ui_TemButton3;
extern lv_obj_t * ui_Label12;
void ui_event_HumButton3(lv_event_t * e);
extern lv_obj_t * ui_HumButton3;
extern lv_obj_t * ui_Label13;
void ui_event_InputButton3(lv_event_t * e);
extern lv_obj_t * ui_InputButton3;
extern lv_obj_t * ui_Label14;
void ui_event_OutputButton3(lv_event_t * e);
extern lv_obj_t * ui_OutputButton3;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_HumChart;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Hum_Panel;
extern lv_obj_t * ui_humvalue;
extern lv_chart_series_t * ui_HumChart_series_1;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Container6;
void ui_event_HomeButton4(lv_event_t * e);
extern lv_obj_t * ui_HomeButton4;
extern lv_obj_t * ui_Label27;
void ui_event_TempButton4(lv_event_t * e);
extern lv_obj_t * ui_TempButton4;
extern lv_obj_t * ui_Label16;
void ui_event_HumButton4(lv_event_t * e);
extern lv_obj_t * ui_HumButton4;
extern lv_obj_t * ui_Label17;
void ui_event_InputButton4(lv_event_t * e);
extern lv_obj_t * ui_InputButton4;
extern lv_obj_t * ui_Label18;
void ui_event_OutputButton4(lv_event_t * e);
extern lv_obj_t * ui_OutputButton4;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Input1;
extern lv_obj_t * ui_Input2;
extern lv_obj_t * ui_Input3;
extern lv_obj_t * ui_Input4;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Labl1;
extern lv_obj_t * ui_Labl2;
extern lv_obj_t * ui_Labl3;
extern lv_obj_t * ui_Labl4;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Container7;
void ui_event_HomeButton5(lv_event_t * e);
extern lv_obj_t * ui_HomeButton5;
extern lv_obj_t * ui_Label28;
void ui_event_TempButton5(lv_event_t * e);
extern lv_obj_t * ui_TempButton5;
extern lv_obj_t * ui_Label20;
void ui_event_HumButton5(lv_event_t * e);
extern lv_obj_t * ui_HumButton5;
extern lv_obj_t * ui_Label21;
void ui_event_InputButton5(lv_event_t * e);
extern lv_obj_t * ui_InputButton5;
extern lv_obj_t * ui_Label22;
void ui_event_OutputButton5(lv_event_t * e);
extern lv_obj_t * ui_OutputButton5;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Container9;
void ui_event_ledSwitch2(lv_event_t * e);
extern lv_obj_t * ui_ledSwitch2;
void ui_event_ledSwitch3(lv_event_t * e);
extern lv_obj_t * ui_ledSwitch3;
void ui_event_ledSwitch4(lv_event_t * e);
extern lv_obj_t * ui_ledSwitch4;
void ui_event_ledSwitch1(lv_event_t * e);
extern lv_obj_t * ui_ledSwitch1;
extern lv_obj_t * ui_Indicator1;
extern lv_obj_t * ui_Indicator2;
extern lv_obj_t * ui_Indicator3;
extern lv_obj_t * ui_Indicator4;
extern lv_obj_t * ui____initial_actions0;










void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
