// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SQ_tft

#include "ui.h"
#include <Arduino.h>

bool led1 = true; 
bool led2 = true; 
void ledoff1(lv_event_t * e)
{
  led1 = false;
  //printf("led off \n");
}

void ledon1(lv_event_t * e)
{
  led1 = true;
  //printf("led on \n");
}
void ledoff2(lv_event_t * e)
{
  led2 = false;
  //printf("led off \n");
}

void ledon2(lv_event_t * e)
{
  led2 = true;
  //printf("led on \n");
}

// void led_event2(lv_event_t * e)
// {
// 	// Your code here
// }

void led_event3(lv_event_t * e)
{
	// Your code here
}

void led_event4(lv_event_t * e)
{
	// Your code here
}

// void led__event1(lv_event_t * e)
// {
// 	// Your code here
// }
