// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SQ_tft

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif
extern bool led1;
extern bool led2;
void ledoff1(lv_event_t * e);
void ledon1(lv_event_t * e);
void ledoff2(lv_event_t * e);
void ledon2(lv_event_t * e);

//void led_event2(lv_event_t * e);
void led_event3(lv_event_t * e);
void led_event4(lv_event_t * e);
// void led__event1(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
