// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SQ_tft

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 95);
    lv_obj_set_height(ui_Container1, 239);
    lv_obj_set_x(ui_Container1, 111);
    lv_obj_set_y(ui_Container1, -1);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton1 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_HomeButton1, 84);
    lv_obj_set_height(ui_HomeButton1, 40);
    lv_obj_set_x(ui_HomeButton1, 2);
    lv_obj_set_y(ui_HomeButton1, -42);
    lv_obj_set_align(ui_HomeButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeButton1, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButton1, lv_color_hex(0x56667B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_HomeButton1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label10 = lv_label_create(ui_HomeButton1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "HOME");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempButton1 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_TempButton1, 84);
    lv_obj_set_height(ui_TempButton1, 31);
    lv_obj_set_x(ui_TempButton1, 3);
    lv_obj_set_y(ui_TempButton1, -88);
    lv_obj_set_align(ui_TempButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TempButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TempButton1, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempButton1, lv_color_hex(0x53657B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_TempButton1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label1 = lv_label_create(ui_TempButton1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Temperature");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumButton1 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_HumButton1, 84);
    lv_obj_set_height(ui_HumButton1, 31);
    lv_obj_set_x(ui_HumButton1, 2);
    lv_obj_set_y(ui_HumButton1, 5);
    lv_obj_set_align(ui_HumButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HumButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HumButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HumButton1, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HumButton1, lv_color_hex(0x506074), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_HumButton1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label2 = lv_label_create(ui_HumButton1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Humidity");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InputButton1 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_InputButton1, 84);
    lv_obj_set_height(ui_InputButton1, 31);
    lv_obj_set_x(ui_InputButton1, 1);
    lv_obj_set_y(ui_InputButton1, 52);
    lv_obj_set_align(ui_InputButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InputButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_InputButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InputButton1, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InputButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_InputButton1, lv_color_hex(0x636A82), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_InputButton1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label3 = lv_label_create(ui_InputButton1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Input");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label3, lv_color_hex(0x505E70), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_OutputButton1 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_OutputButton1, 84);
    lv_obj_set_height(ui_OutputButton1, 31);
    lv_obj_set_x(ui_OutputButton1, 3);
    lv_obj_set_y(ui_OutputButton1, 96);
    lv_obj_set_align(ui_OutputButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OutputButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OutputButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OutputButton1, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OutputButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OutputButton1, lv_color_hex(0x636D85), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_OutputButton1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label4 = lv_label_create(ui_OutputButton1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Output");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 193);
    lv_obj_set_height(ui_Container2, 229);
    lv_obj_set_x(ui_Container2, -45);
    lv_obj_set_y(ui_Container2, -1);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempPanel = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_TempPanel, 80);
    lv_obj_set_height(ui_TempPanel, 79);
    lv_obj_set_x(ui_TempPanel, 7);
    lv_obj_set_y(ui_TempPanel, -49);
    lv_obj_set_align(ui_TempPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TempPanel, 280, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TempPanel, 67, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Tempvalue = lv_label_create(ui_TempPanel);
    lv_obj_set_width(ui_Tempvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tempvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Tempvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Tempvalue, "0");
    lv_obj_set_style_text_font(ui_Tempvalue, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumPanel = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_HumPanel, 82);
    lv_obj_set_height(ui_HumPanel, 80);
    lv_obj_set_x(ui_HumPanel, 8);
    lv_obj_set_y(ui_HumPanel, 61);
    lv_obj_set_align(ui_HumPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HumPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HumPanel, 280, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_HumPanel, 67, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Humvalue = lv_label_create(ui_HumPanel);
    lv_obj_set_width(ui_Humvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Humvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humvalue, "0");
    lv_obj_set_style_text_font(ui_Humvalue, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 9);
    lv_obj_set_y(ui_Label5, -101);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Temperature");

    ui_Label7 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 9);
    lv_obj_set_y(ui_Label7, 7);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Humidity");

    lv_obj_add_event_cb(ui_HomeButton1, ui_event_HomeButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempButton1, ui_event_TempButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HumButton1, ui_event_HumButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InputButton1, ui_event_InputButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OutputButton1, ui_event_OutputButton1, LV_EVENT_ALL, NULL);

}
