// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SQ_tft

#include "ui.h"
lv_chart_series_t * ui_TempChart_series_1 = NULL;

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container4 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 85);
    lv_obj_set_height(ui_Container4, 239);
    lv_obj_set_x(ui_Container4, 116);
    lv_obj_set_y(ui_Container4, -1);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton2 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_HomeButton2, 84);
    lv_obj_set_height(ui_HomeButton2, 40);
    lv_obj_set_x(ui_HomeButton2, 2);
    lv_obj_set_y(ui_HomeButton2, -42);
    lv_obj_set_align(ui_HomeButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeButton2, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButton2, lv_color_hex(0x56667B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_HomeButton2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label25 = lv_label_create(ui_HomeButton2);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "HOME");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempButton2 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_TempButton2, 84);
    lv_obj_set_height(ui_TempButton2, 31);
    lv_obj_set_x(ui_TempButton2, 3);
    lv_obj_set_y(ui_TempButton2, -88);
    lv_obj_set_align(ui_TempButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TempButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TempButton2, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempButton2, lv_color_hex(0x53657B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_TempButton2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label11 = lv_label_create(ui_TempButton2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Temperature");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumButton2 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_HumButton2, 84);
    lv_obj_set_height(ui_HumButton2, 31);
    lv_obj_set_x(ui_HumButton2, 2);
    lv_obj_set_y(ui_HumButton2, 5);
    lv_obj_set_align(ui_HumButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HumButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HumButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HumButton2, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HumButton2, lv_color_hex(0x506074), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_HumButton2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label6 = lv_label_create(ui_HumButton2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Humidity");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InputButton2 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_InputButton2, 84);
    lv_obj_set_height(ui_InputButton2, 31);
    lv_obj_set_x(ui_InputButton2, 1);
    lv_obj_set_y(ui_InputButton2, 52);
    lv_obj_set_align(ui_InputButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InputButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_InputButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InputButton2, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InputButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_InputButton2, lv_color_hex(0x636A82), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_InputButton2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label8 = lv_label_create(ui_InputButton2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Input");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label8, lv_color_hex(0x505E70), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_OutputButton2 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_OutputButton2, 84);
    lv_obj_set_height(ui_OutputButton2, 31);
    lv_obj_set_x(ui_OutputButton2, 3);
    lv_obj_set_y(ui_OutputButton2, 96);
    lv_obj_set_align(ui_OutputButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OutputButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OutputButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OutputButton2, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OutputButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OutputButton2, lv_color_hex(0x636D85), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_OutputButton2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label9 = lv_label_create(ui_OutputButton2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Output");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp_Panel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Temp_Panel, 66);
    lv_obj_set_height(ui_Temp_Panel, 28);
    lv_obj_set_x(ui_Temp_Panel, -3);
    lv_obj_set_y(ui_Temp_Panel, -95);
    lv_obj_set_align(ui_Temp_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Temp_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempvalue = lv_label_create(ui_Temp_Panel);
    lv_obj_set_width(ui_tempvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tempvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempvalue, "0");

    ui_TempChart = lv_chart_create(ui_Screen2);
    lv_obj_set_width(ui_TempChart, 192);
    lv_obj_set_height(ui_TempChart, 158);
    lv_obj_set_x(ui_TempChart, -34);
    lv_obj_set_y(ui_TempChart, 13);
    lv_obj_set_align(ui_TempChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_TempChart, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_TempChart, LV_CHART_AXIS_PRIMARY_Y, 0, 50);
    lv_chart_set_div_line_count(ui_TempChart, 20, 10);
    lv_chart_set_axis_tick(ui_TempChart, LV_CHART_AXIS_PRIMARY_X, 5, 1, 10, 1, true, 50);
    lv_chart_set_axis_tick(ui_TempChart, LV_CHART_AXIS_PRIMARY_Y, 5, 1, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_TempChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    ui_TempChart_series_1 = lv_chart_add_series(ui_TempChart, lv_color_hex(0x8C2323),
                                                                    LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_TempChart_series_1_array[24] = { 0 };
    lv_chart_set_ext_y_array(ui_TempChart, ui_TempChart_series_1, ui_TempChart_series_1_array);



    lv_obj_set_style_text_font(ui_TempChart, &lv_font_montserrat_10, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -95);
    lv_obj_set_y(ui_Label24, -96);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "TEMPERATURE");
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeButton2, ui_event_HomeButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempButton2, ui_event_TempButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HumButton2, ui_event_HumButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InputButton2, ui_event_InputButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OutputButton2, ui_event_OutputButton2, LV_EVENT_ALL, NULL);

}
