// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SQ_tft

#include "ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container7 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 95);
    lv_obj_set_height(ui_Container7, 239);
    lv_obj_set_x(ui_Container7, 111);
    lv_obj_set_y(ui_Container7, -1);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton5 = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_HomeButton5, 84);
    lv_obj_set_height(ui_HomeButton5, 40);
    lv_obj_set_x(ui_HomeButton5, 2);
    lv_obj_set_y(ui_HomeButton5, -42);
    lv_obj_set_align(ui_HomeButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeButton5, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButton5, lv_color_hex(0x56667B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_HomeButton5, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label28 = lv_label_create(ui_HomeButton5);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "HOME");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempButton5 = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_TempButton5, 84);
    lv_obj_set_height(ui_TempButton5, 31);
    lv_obj_set_x(ui_TempButton5, 3);
    lv_obj_set_y(ui_TempButton5, -88);
    lv_obj_set_align(ui_TempButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TempButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TempButton5, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempButton5, lv_color_hex(0x53657B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_TempButton5, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label20 = lv_label_create(ui_TempButton5);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Temperature");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumButton5 = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_HumButton5, 84);
    lv_obj_set_height(ui_HumButton5, 31);
    lv_obj_set_x(ui_HumButton5, 2);
    lv_obj_set_y(ui_HumButton5, 5);
    lv_obj_set_align(ui_HumButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HumButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HumButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HumButton5, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HumButton5, lv_color_hex(0x506074), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_HumButton5, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label21 = lv_label_create(ui_HumButton5);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Humidity");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InputButton5 = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_InputButton5, 84);
    lv_obj_set_height(ui_InputButton5, 31);
    lv_obj_set_x(ui_InputButton5, 1);
    lv_obj_set_y(ui_InputButton5, 52);
    lv_obj_set_align(ui_InputButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InputButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_InputButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InputButton5, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InputButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_InputButton5, lv_color_hex(0x636A82), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_InputButton5, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label22 = lv_label_create(ui_InputButton5);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Input");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label22, lv_color_hex(0x505E70), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_OutputButton5 = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_OutputButton5, 84);
    lv_obj_set_height(ui_OutputButton5, 31);
    lv_obj_set_x(ui_OutputButton5, 3);
    lv_obj_set_y(ui_OutputButton5, 96);
    lv_obj_set_align(ui_OutputButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OutputButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OutputButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OutputButton5, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OutputButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OutputButton5, lv_color_hex(0x636D85), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_OutputButton5, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label23 = lv_label_create(ui_OutputButton5);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Output");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 178);
    lv_obj_set_height(ui_Container9, 214);
    lv_obj_set_x(ui_Container9, -36);
    lv_obj_set_y(ui_Container9, 1);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ledSwitch2 = lv_switch_create(ui_Container9);
    lv_obj_set_width(ui_ledSwitch2, 50);
    lv_obj_set_height(ui_ledSwitch2, 25);
    lv_obj_set_x(ui_ledSwitch2, 30);
    lv_obj_set_y(ui_ledSwitch2, -26);
    lv_obj_set_align(ui_ledSwitch2, LV_ALIGN_CENTER);


    ui_ledSwitch3 = lv_switch_create(ui_Container9);
    lv_obj_set_width(ui_ledSwitch3, 50);
    lv_obj_set_height(ui_ledSwitch3, 25);
    lv_obj_set_x(ui_ledSwitch3, 30);
    lv_obj_set_y(ui_ledSwitch3, 21);
    lv_obj_set_align(ui_ledSwitch3, LV_ALIGN_CENTER);


    ui_ledSwitch4 = lv_switch_create(ui_Container9);
    lv_obj_set_width(ui_ledSwitch4, 50);
    lv_obj_set_height(ui_ledSwitch4, 25);
    lv_obj_set_x(ui_ledSwitch4, 30);
    lv_obj_set_y(ui_ledSwitch4, 69);
    lv_obj_set_align(ui_ledSwitch4, LV_ALIGN_CENTER);


    ui_ledSwitch1 = lv_switch_create(ui_Container9);
    lv_obj_set_width(ui_ledSwitch1, 50);
    lv_obj_set_height(ui_ledSwitch1, 25);
    lv_obj_set_x(ui_ledSwitch1, 30);
    lv_obj_set_y(ui_ledSwitch1, -76);
    lv_obj_set_align(ui_ledSwitch1, LV_ALIGN_CENTER);


    ui_Indicator1 = lv_obj_create(ui_Container9);
    lv_obj_set_width(ui_Indicator1, 23);
    lv_obj_set_height(ui_Indicator1, 23);
    lv_obj_set_x(ui_Indicator1, -60);
    lv_obj_set_y(ui_Indicator1, -77);
    lv_obj_set_align(ui_Indicator1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Indicator1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Indicator1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Indicator2 = lv_obj_create(ui_Container9);
    lv_obj_set_width(ui_Indicator2, 23);
    lv_obj_set_height(ui_Indicator2, 23);
    lv_obj_set_x(ui_Indicator2, -60);
    lv_obj_set_y(ui_Indicator2, -26);
    lv_obj_set_align(ui_Indicator2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Indicator2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Indicator2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Indicator3 = lv_obj_create(ui_Container9);
    lv_obj_set_width(ui_Indicator3, 23);
    lv_obj_set_height(ui_Indicator3, 23);
    lv_obj_set_x(ui_Indicator3, -60);
    lv_obj_set_y(ui_Indicator3, 21);
    lv_obj_set_align(ui_Indicator3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Indicator3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Indicator3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Indicator4 = lv_obj_create(ui_Container9);
    lv_obj_set_width(ui_Indicator4, 23);
    lv_obj_set_height(ui_Indicator4, 23);
    lv_obj_set_x(ui_Indicator4, -60);
    lv_obj_set_y(ui_Indicator4, 69);
    lv_obj_set_align(ui_Indicator4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Indicator4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Indicator4, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeButton5, ui_event_HomeButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempButton5, ui_event_TempButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HumButton5, ui_event_HumButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InputButton5, ui_event_InputButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OutputButton5, ui_event_OutputButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ledSwitch2, ui_event_ledSwitch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ledSwitch3, ui_event_ledSwitch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ledSwitch4, ui_event_ledSwitch4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ledSwitch1, ui_event_ledSwitch1, LV_EVENT_ALL, NULL);

}
