// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SQ_tft

#include "ui.h"
lv_chart_series_t * ui_HumChart_series_1 = NULL;

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container5 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 95);
    lv_obj_set_height(ui_Container5, 239);
    lv_obj_set_x(ui_Container5, 111);
    lv_obj_set_y(ui_Container5, -1);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton3 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_HomeButton3, 84);
    lv_obj_set_height(ui_HomeButton3, 40);
    lv_obj_set_x(ui_HomeButton3, 2);
    lv_obj_set_y(ui_HomeButton3, -42);
    lv_obj_set_align(ui_HomeButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeButton3, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButton3, lv_color_hex(0x56667B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_HomeButton3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label26 = lv_label_create(ui_HomeButton3);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "HOME");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemButton3 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_TemButton3, 84);
    lv_obj_set_height(ui_TemButton3, 31);
    lv_obj_set_x(ui_TemButton3, 3);
    lv_obj_set_y(ui_TemButton3, -88);
    lv_obj_set_align(ui_TemButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TemButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TemButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TemButton3, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TemButton3, lv_color_hex(0x53657B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_TemButton3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label12 = lv_label_create(ui_TemButton3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Temperature");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumButton3 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_HumButton3, 84);
    lv_obj_set_height(ui_HumButton3, 31);
    lv_obj_set_x(ui_HumButton3, 2);
    lv_obj_set_y(ui_HumButton3, 5);
    lv_obj_set_align(ui_HumButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HumButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HumButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HumButton3, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HumButton3, lv_color_hex(0x506074), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_HumButton3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label13 = lv_label_create(ui_HumButton3);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Humidity");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InputButton3 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_InputButton3, 84);
    lv_obj_set_height(ui_InputButton3, 31);
    lv_obj_set_x(ui_InputButton3, 1);
    lv_obj_set_y(ui_InputButton3, 52);
    lv_obj_set_align(ui_InputButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InputButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_InputButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InputButton3, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InputButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_InputButton3, lv_color_hex(0x636A82), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_InputButton3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label14 = lv_label_create(ui_InputButton3);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Input");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label14, lv_color_hex(0x505E70), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_OutputButton3 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_OutputButton3, 84);
    lv_obj_set_height(ui_OutputButton3, 31);
    lv_obj_set_x(ui_OutputButton3, 3);
    lv_obj_set_y(ui_OutputButton3, 96);
    lv_obj_set_align(ui_OutputButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OutputButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OutputButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OutputButton3, lv_color_hex(0x375374), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OutputButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OutputButton3, lv_color_hex(0x636D85), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_OutputButton3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label15 = lv_label_create(ui_OutputButton3);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Output");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumChart = lv_chart_create(ui_Screen3);
    lv_obj_set_width(ui_HumChart, 192);
    lv_obj_set_height(ui_HumChart, 158);
    lv_obj_set_x(ui_HumChart, -34);
    lv_obj_set_y(ui_HumChart, 13);
    lv_obj_set_align(ui_HumChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_HumChart, LV_CHART_TYPE_LINE);
    lv_chart_set_div_line_count(ui_HumChart, 20, 10);
    lv_chart_set_axis_tick(ui_HumChart, LV_CHART_AXIS_PRIMARY_X, 5, 1, 10, 1, true, 50);
    lv_chart_set_axis_tick(ui_HumChart, LV_CHART_AXIS_PRIMARY_Y, 5, 1, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_HumChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    ui_HumChart_series_1 = lv_chart_add_series(ui_HumChart, lv_color_hex(0x8C2323),
                                                                   LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_HumChart_series_1_array[24] = { 0 };
    lv_chart_set_ext_y_array(ui_HumChart, ui_HumChart_series_1, ui_HumChart_series_1_array);



    lv_obj_set_style_text_font(ui_HumChart, &lv_font_montserrat_10, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, -95);
    lv_obj_set_y(ui_Label31, -96);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "HUMIDITY");
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hum_Panel = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Hum_Panel, 66);
    lv_obj_set_height(ui_Hum_Panel, 28);
    lv_obj_set_x(ui_Hum_Panel, -9);
    lv_obj_set_y(ui_Hum_Panel, -95);
    lv_obj_set_align(ui_Hum_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Hum_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humvalue = lv_label_create(ui_Hum_Panel);
    lv_obj_set_width(ui_humvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_humvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humvalue, "0");

    lv_obj_add_event_cb(ui_HomeButton3, ui_event_HomeButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TemButton3, ui_event_TemButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HumButton3, ui_event_HumButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InputButton3, ui_event_InputButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OutputButton3, ui_event_OutputButton3, LV_EVENT_ALL, NULL);

}
