// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: output_display

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Labl1;
lv_obj_t * ui_Labl2;
lv_obj_t * ui_Labl3;
lv_obj_t * ui_Labl4;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_dacvoltageLabel;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_daccurrentLabel;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Indicator4;
lv_obj_t * ui_Indicator3;
lv_obj_t * ui_Indicator2;
lv_obj_t * ui_Indicator1;
void ui_event_ledSwitch4(lv_event_t * e);
lv_obj_t * ui_ledSwitch4;
void ui_event_ledSwitch3(lv_event_t * e);
lv_obj_t * ui_ledSwitch3;
void ui_event_ledSwitch2(lv_event_t * e);
lv_obj_t * ui_ledSwitch2;
void ui_event_ledSwitch1(lv_event_t * e);
lv_obj_t * ui_ledSwitch1;
void ui_event_daccurrentSlider(lv_event_t * e);
lv_obj_t * ui_daccurrentSlider;
void ui_event_dacvoltageSlider(lv_event_t * e);
lv_obj_t * ui_dacvoltageSlider;
lv_obj_t * ui_Label4;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ledSwitch4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        led_event4(e);
        _ui_state_modify(ui_Indicator4, LV_STATE_USER_1, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_ledSwitch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        led_event3(e);
        _ui_state_modify(ui_Indicator3, LV_STATE_USER_1, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_ledSwitch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        led_event2(e);
        _ui_state_modify(ui_Indicator2, LV_STATE_USER_1, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_ledSwitch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        led_event1(e);
        _ui_state_modify(ui_Indicator1, LV_STATE_USER_1, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_daccurrentSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_daccurrentLabel, target, "", " mA");
        sldr_current_dac(e);
    }
}
void ui_event_dacvoltageSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_dacvoltageLabel, target, "", " V");
        sldr_voltage_dac(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
