// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: store_ui

#ifndef _STORE_UI_UI_H
#define _STORE_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_timeLabel;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_weightLabel;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Dropdown;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
void ui_event_clearButton(lv_event_t * e);
extern lv_obj_t * ui_clearButton;
extern lv_obj_t * ui_Label9;
void ui_event_submitButton(lv_event_t * e);
extern lv_obj_t * ui_submitButton;
extern lv_obj_t * ui_Label10;
void ui_event_opidTextArea(lv_event_t * e);
extern lv_obj_t * ui_opidTextArea;
void ui_event_regionTextArea(lv_event_t * e);
extern lv_obj_t * ui_regionTextArea;
void ui_event_snameTextArea(lv_event_t * e);
extern lv_obj_t * ui_snameTextArea;
void ui_event_sidTextArea(lv_event_t * e);
extern lv_obj_t * ui_sidTextArea;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_qrLabel;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container;
extern lv_obj_t * ui_TextArea;
void ui_event_Keyboard(lv_event_t * e);
extern lv_obj_t * ui_Keyboard;
// CUSTOM VARIABLES

extern lv_obj_t* previous_screen;
extern lv_obj_t* active_textarea;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
