// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: store_ui

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xD3CA85), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 784);
    lv_obj_set_height(ui_Container1, 471);
    lv_obj_set_x(ui_Container1, 1);
    lv_obj_set_y(ui_Container1, 1);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -302);
    lv_obj_set_y(ui_Label1, -123);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Time/Date:");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Panel1, 694);
    lv_obj_set_height(ui_Panel1, 66);
    lv_obj_set_x(ui_Panel1, -12);
    lv_obj_set_y(ui_Panel1, -74);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLabel = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_timeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_timeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLabel, "");
    lv_obj_set_style_text_font(ui_timeLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 95);
    lv_obj_set_y(ui_Label2, -217);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "QR Barcode:");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -321);
    lv_obj_set_y(ui_Label3, -216);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Weight:");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Panel2, 290);
    lv_obj_set_height(ui_Panel2, 57);
    lv_obj_set_x(ui_Panel2, -211);
    lv_obj_set_y(ui_Panel2, -170);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weightLabel = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_weightLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weightLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weightLabel, -12);
    lv_obj_set_y(ui_weightLabel, 0);
    lv_obj_set_align(ui_weightLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weightLabel, "");
    lv_obj_set_style_text_font(ui_weightLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -318);
    lv_obj_set_y(ui_Label4, -22);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Op ID:");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -310);
    lv_obj_set_y(ui_Label5, 69);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Store ID:");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -291);
    lv_obj_set_y(ui_Label6, 161);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Store Name:");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown = lv_dropdown_create(ui_Container1);
    lv_dropdown_set_options(ui_Dropdown, "                             -        \nWHEAT\nRICE\nMILLET");
    lv_obj_set_width(ui_Dropdown, 290);
    lv_obj_set_height(ui_Dropdown, 50);
    lv_obj_set_x(ui_Dropdown, 185);
    lv_obj_set_y(ui_Dropdown, 19);
    lv_obj_set_align(ui_Dropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_border_color(ui_Dropdown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown), &lv_font_montserrat_16,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_Dropdown), lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_Dropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown), &lv_font_montserrat_22,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 66);
    lv_obj_set_y(ui_Label7, -19);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Item:");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 77);
    lv_obj_set_y(ui_Label8, 68);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Region:");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clearButton = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_clearButton, 100);
    lv_obj_set_height(ui_clearButton, 32);
    lv_obj_set_x(ui_clearButton, 99);
    lv_obj_set_y(ui_clearButton, 197);
    lv_obj_set_align(ui_clearButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clearButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_clearButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clearButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clearButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_clearButton);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Clear");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_submitButton = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_submitButton, 118);
    lv_obj_set_height(ui_submitButton, 61);
    lv_obj_set_x(ui_submitButton, 268);
    lv_obj_set_y(ui_submitButton, 197);
    lv_obj_set_align(ui_submitButton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_submitButton, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_submitButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_submitButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_submitButton, lv_color_hex(0xA59D9D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_submitButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_submitButton, lv_color_hex(0x00DD18), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_submitButton, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Label10 = lv_label_create(ui_submitButton);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Submit");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_opidTextArea = lv_textarea_create(ui_Container1);
    lv_obj_set_width(ui_opidTextArea, 290);
    lv_obj_set_height(ui_opidTextArea, 57);
    lv_obj_set_x(ui_opidTextArea, -212);
    lv_obj_set_y(ui_opidTextArea, 18);
    lv_obj_set_align(ui_opidTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_opidTextArea, "");
    lv_obj_set_style_text_align(ui_opidTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_opidTextArea, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_opidTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_opidTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_regionTextArea = lv_textarea_create(ui_Container1);
    lv_obj_set_width(ui_regionTextArea, 290);
    lv_obj_set_height(ui_regionTextArea, 57);
    lv_obj_set_x(ui_regionTextArea, 185);
    lv_obj_set_y(ui_regionTextArea, 116);
    lv_obj_set_align(ui_regionTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_regionTextArea, "");
    lv_obj_set_style_text_align(ui_regionTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_regionTextArea, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_regionTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_regionTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_snameTextArea = lv_textarea_create(ui_Container1);
    lv_obj_set_width(ui_snameTextArea, 290);
    lv_obj_set_height(ui_snameTextArea, 57);
    lv_obj_set_x(ui_snameTextArea, -212);
    lv_obj_set_y(ui_snameTextArea, 205);
    lv_obj_set_align(ui_snameTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_snameTextArea, "");
    lv_obj_set_style_text_align(ui_snameTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_snameTextArea, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_snameTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_snameTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_sidTextArea = lv_textarea_create(ui_Container1);
    lv_obj_set_width(ui_sidTextArea, 290);
    lv_obj_set_height(ui_sidTextArea, 57);
    lv_obj_set_x(ui_sidTextArea, -212);
    lv_obj_set_y(ui_sidTextArea, 112);
    lv_obj_set_align(ui_sidTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_sidTextArea, "");
    lv_obj_set_style_text_align(ui_sidTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sidTextArea, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sidTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sidTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Panel3 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Panel3, 290);
    lv_obj_set_height(ui_Panel3, 57);
    lv_obj_set_x(ui_Panel3, 185);
    lv_obj_set_y(ui_Panel3, -170);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_qrLabel = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_qrLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_qrLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_qrLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_qrLabel, "");
    lv_obj_set_style_text_font(ui_qrLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -130);
    lv_obj_set_y(ui_Label11, -169);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Kg");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_clearButton, ui_event_clearButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_submitButton, ui_event_submitButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_opidTextArea, ui_event_opidTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_regionTextArea, ui_event_regionTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_snameTextArea, ui_event_snameTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sidTextArea, ui_event_sidTextArea, LV_EVENT_ALL, NULL);

}
