// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: IOI_Project

#include "ui.h"

void led_event4(lv_event_t * e)
{
	// Your code here
}

void led_event3(lv_event_t * e)
{
	// Your code here
}

void led_event2(lv_event_t * e)
{
	// Your code here
}

void led_event1(lv_event_t * e)
{
	// Your code here
}

void sldr_current_dac(lv_event_t * e)
{
	// Your code here
}

void sldr_voltage_dac(lv_event_t * e)
{
	// Your code here
}
